### ISSUE TITLE
Student Work Upload, Comments Button Not Triggering

### ISSUE THREAD

**Issue by JoeSpan** [smiths/MEASURE#101]
When I am trying to upload student's work in the Rubric Input Template, the comments button does not trigger when trying to upload student work. I press it and nothing happens
@smiths 

![image](https://cloud.githubusercontent.com/assets/20819724/20436019/6185dffe-ad7c-11e6-946a-1a267131bdb3.png)

**Comment by smiths** [comment]
Hello Joe.  I had the same problem with a randomly selected rubric.  If I clicked on the grey cell (the indicator name), I could add a comment, but it didn't work for the "white" or editable cell.

@EvanVena, do you know what might have happened here?  This used to work.  I am using Excel 2013.  (I'm not sure of the version that Joe is using.)

**Comment by EvanVena** [comment]
@JoeSpan @smiths  
I might know what happen, can you please provide what course/term/section you are trying to add comment?

**Comment by JoeSpan** [comment]
So I tested this on both mech eng 4T03 and 2P04 for 2016-2016 term 1 section 1. The problem is now not there in either of them so I am assuming whatever you did worked wonders. @EvanVena

**Comment by JoeSpan** [comment]
@smiths can you confirm that it now works for you? I think we can close this issue now.

**Comment by smiths** [comment]
The comments worked for MECH ENG 4T03 and 2P04 for 2015-2016, Term 1.  I selected a course randomly last time, so I'm not sure what led to the problem.  I will close this issue.  @JoeSpan , if you notice the problem again, please post an issue, along with the specific course, year, term and section.  I'll do the same.
