### ISSUE TITLE
Remove course?

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#102]
Hello @EvanVena .  Michelle ( @zhengm2 ) and I had a meeting with the departments today and an important question came up.  We have instructions in our manual for adding courses, but we do not have instructions for removing courses.  The case is currently coming up where courses are no longer part of a degree program, although they may be part of another degree program.  Even if the course is no longer offered, we don't want to lose any previous data recorded for it.  How do we remove a course from a program, but keep it in other programs?  Using delete from the modeler view seems to extreme based on the message that is displayed.  I'll attach the screen that we are seeing for a randomly selected course (CHEM ENG 2F04).

![removecourse](https://cloud.githubusercontent.com/assets/1422000/20492147/ab11d17a-afe1-11e6-9114-0c58a9857b73.png)

**Comment by EvanVena** [comment]
@smiths @JoeSpan 
there is a Unmapped Program folder set up, you can move the course that is not currently offer to this parent node. (PS: since we are using share member, when you move one of them to "Unmapped", you can safely delete the rest of them in the regular course hierarchy. )

Thanks
Evan

**Comment by smiths** [comment]
Great!  Thank you Evan.  @zhengm2 , can you please add instructions to our departmental manual for "removing" a course.  We can close this issue once that is done.  Thank you.

**Comment by zhengm2** [comment]
This has been added to section 6.

**Comment by smiths** [comment]
Looks good @zhengm2.  Have you shared this information with the departments?  Can you please CC me on any e-mails to the departmental representatives.

**Comment by smiths** [comment]
@EvanVena, if a course is no longer part of a specific program, but it is still offered in other programs, do we right click on the course in the program where it is to be removed and select cut (like what Michelle describes on page 10 of the departmental guide)?  This makes sense to me, but I want to verify before clarifying the language in the departmental guide.

**Comment by EvanVena** [comment]
Hi Spencer,

as far as you still have the course attached to other program, you can
ignore the message and delete the course.

after deleted the course, you can go to Modeler --> ETL -->Export -->
select value
to confirm, all the data should still there.

Evan

**Comment by smiths** [comment]
Thank you Evan.  @zhengm2, can you please test @EvanVena instructions and then update the departmental guide to reflect this information.  For removing a course, we want to explain two cases:
1. The course is no longer offered and will be removed from all programs.  In that case we move it to unmapped and follow the instructions that you put in the Departmental Guide.
2. The course is removed from one program, but still offered in others, we follow the instructions given above by Evan.

**Comment by zhengm2** [comment]
Hi @smiths,

Yes, this works and I have confirmed that the data is still there. I will be pushing the guide to GitHub in a few seconds and sending it out.

**Comment by smiths** [comment]
Great!  Thank you Michelle.
