### ISSUE TITLE
Permission to update model "CEAB Accreditation"?

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#103]
Hello @EvanVena .  Out of the same meeting that I mentioned in issue #102 , @zhengm2 and I found we had another question.  One of our departmental users, who has the role of modeler, needs to make changes to their program, but they are being told that they do not have sufficient permission.  Michelle and I think that there is another step we need to do, besides making someone a modeller.  We remember you doing something about this in the past, but we cannot remember what you did.  I can find the Permissions screen, where the permission for update model "CEAB Accreditation" is listed, but I do not know how to associate that with a specific user.

For this specific case, the user is Tonya Antonecchia.  Michelle added her to the system, instead of you, so we think we missed a step.  Can you please tell us how to get Tonya permission to change the mapping between courses and programs?  Specifically, she needs permission to be able to add new courses to Civil Engineering.

**Comment by EvanVena** [comment]
Done, can you please check
@smiths

**Comment by smiths** [comment]
@EvanVena , I am checking with the departmental rep to see if they now have access.  Can you please tell Michelle ( @zhengm2 ) and I what you did, so that we can add these steps to the Admin Guide?

**Comment by smiths** [comment]
Hi Evan.  I have now verified with Tonya that the changes you made worked.  Can you please let @zhengm2 and I know what you did, so that we can include it in the administrator's guide?

**Comment by smiths** [comment]
A new issue has been created for updating the documentation ( #105).  I'll close this issue.

**Comment by EvanVena** [comment]
Hi @smiths @zhengm2 
after you login to Vena -->Click Admin -->Click Permission -->Click on Modelers -->Click on Manage-->You can search for an user name and add it 

![image](https://cloud.githubusercontent.com/assets/20912011/20574815/6ace7236-b184-11e6-8e42-f497b5a504d2.png)

**Comment by smiths** [comment]
Excellent.  Thank you Evan.  @zhengm2 , can you please add this information to the Admin Guide?
