### ISSUE TITLE
Renaming Programs?

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#104]
Hello @EvanVena .  @zhengm2 and I were wondering if there would be any unforeseen consequences for renaming a program?  When we last entered program data into Vena, McMaster had an International Studies degree program for each department.  That is, we had Chemical Engineering and International Studies, Civil Engineering and International Studies, etc.  We no longer have that program, but we do have a new program option for every department, now for Biomedical engineering.  That is, we have Chemical and Biomedical Engineering, Civil and Biomedical Engineering etc.

Can we simply rename the International Studies options to Biomedical?  It seems to me that the name of the program is just a string, so Vena shouldn't care what we call it.  However, I wanted to check before making the change.

**Comment by EvanVena** [comment]
@smiths @zhengm2 
We should create the new program, since the old data still stored at the old program, and we don't want to merge the data from two programs.
Hope this help,
Evan

**Comment by smiths** [comment]
Hello Evan.  My thinking is that the International Studies options do not really have any data in them.  The curriculum for the biomedical programs is similar to the international studies options.  However, I get your point that in general, renaming programs is not something that we would want to do.
