### ISSUE TITLE
Documentation for adding modellers to the admin guide

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#105]
Hello Evan.  Can you please send @zhengm2 and I instructions for how to add a modeller to Vena so that they have permission to edit the programs for CEAB accreditation?  We first discussed this in #103 .  The documentation will become part of the administrator's guide.

**Comment by EvanVena** [comment]
![image](https://cloud.githubusercontent.com/assets/20912011/20574823/75ed2b62-b184-11e6-9b6d-8ef051cf246d.png)

**Comment by smiths** [comment]
@zhengm2 , can you please add this documentation to the admin guide.  The answer from @EvanVena is given in issue #103.

**Comment by zhengm2** [comment]
Added.

**Comment by smiths** [comment]
Looks good Michelle.  I did make a minor edit to your instructions for giving permissions, to indicate that this is only necessary for departmental representatives in the modeller role.  I pushed my changes to the repo.
