### ISSUE TITLE
Renaming International Studies to Biomedical Engineering

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#106]
Hello Michelle.  Can you please edit the names of the International Studies programs to replace them with the Biomedical Engineering programs?  This issue was discussed in #104.  Evan had a good point that renaming is a problem if there is existing data, but the International Studies courses do not have any data (other than where they overlap with courses that were measured for other programs.)  We are essentially starting our data entry from 2016-2017, so from that point of view International Studies is not relevant at all.

We discussed the idea of repurprosing the International Studies programs in our departmental training session last week.  Rather than get the departments to do this change, I would feel more comfortable if you did it.  The fewer "cooks" in the "kitchen", the better.  :-)

**Comment by zhengm2** [comment]
Hi Spencer, is it an issue that the program doesn't start until 2017-18? I suppose it doesn't make a difference if there isn't any data entered?

**Comment by smiths** [comment]
Hello Michelle.  I think we can go ahead and add biomedical and just not enter the data.  It is on everyone's minds right now, and having international studies in the system doesn't make sense any more.  Having a year without data won't be a problem at all, and actually there will be a history of data for some of the courses, since many of them will be taught for other programs.

Some day we might have to separate out how the students from different programs do in the same course, but at the moment this isn't anywhere near our radar.  :-)

**Comment by zhengm2** [comment]
Hi Spencer,

All programs have been updated.

**Comment by smiths** [comment]
Looks good.  Thank you Michelle.
