### ISSUE TITLE
Verify that the program mappings match the undergraduate calendar

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#107]
Hi Michelle.  Once the departments have updated their program mapping information, could  you please verify that the information is correct?  A mistake here will cause us significant headaches going forward.

**Comment by zhengm2** [comment]
Hi @smiths ,

I am working on this right now. I've heard back from most of the departments that they have completed the mapping and data entry.

**Comment by smiths** [comment]
Great!  Once we get to steady state, I do not think this review will be necessary.  For this time around though, I feel a lot better that you are checking.  :-)

**Comment by smiths** [comment]
Michelle has completed this check, so we will close this issue.
