### ISSUE TITLE
Update List of Contributors

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#108]
Before the instructors can input their rubrics and course reports, we need to make sure that they have accounts in Vena.  Most are already in there, but anyone new in the last two years will need to be added.  Moreover, anyone that has left Mac should be deleted, so that we don't use up more than our allotted number of licenses.

**Comment by zhengm2** [comment]
Hi @smiths ,

Do you know how many licenses we have? I'm going over the lists now and have identified a few that can be removed. I will be emailing the departments to inquire if their sessionals need to be set up or the data will be entered for them.

Thanks,
Michelle

**Comment by smiths** [comment]
Hello Michelle.  I just looked over the Vena quote, and it looks to me like we have 250 users.  I thought it was fewer, so we have a greater margin than I expected.

**Comment by zhengm2** [comment]
Thanks Spencer. I think it will be around 200 after all of the changes are made.

**Comment by smiths** [comment]
Great!

**Comment by zhengm2** [comment]
I'm leaving this open for now as I haven't hear back from all departments yet regarding sessional lecturers. However, the majority of users have been updated.

**Comment by smiths** [comment]
That sounds prudent Michelle.  Unfortunately, there will be people that come out of the woodwork once we have started with the instructors entering data.  For some reason it is inevitable that some will ignore our messages until past the last minute.  :-(

**Comment by smiths** [comment]
I'll close this issue now, since there is no overt action on our part necessary.  If someone complains they do not have an account, we'll deal with it on a case by case basis.
