### ISSUE TITLE
Add Instructors as Support Workers for the "Rubric Input and Course Report (by Instructor)" Template

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#110]
Hello Michelle.  We are now ready to enable the instructors for entering their rubric and course report data.  Can you please do this?  It will take some time mouse clicking, but it should be fairly easy.  We add the users following the steps outlined in Section 5 of the Admin Guide: Assign User to Process.  The task you want to assign users to is "Rubric Input & Course Report (by Instructor) -New."  The instructors should be added as Support Workers.  You will need to add every instructor.  Please let me know if you have any questions.

By the way, we are adding the instructors as Support Workers, so that they do not have access to the Submit button.  As of right now, only you and me are owners of this task.  We are the only ones that can submit it.  We should do the submission before archiving the data for a given year.  I'm adding words to this effect to the Admin Guide.

**Comment by zhengm2** [comment]
Hi Spencer,

All instructors have been added.

**Comment by smiths** [comment]
Excellent.  Thank you Michelle.
