### ISSUE TITLE
Historical Program Measurement Archive (Task 9 of the Admin Guide) - Unable to import the the AcademicYearTemplate.csv

### ISSUE THREAD

**Issue by arana2** [smiths/MEASURE#118]
Hello @smiths ,

I am following the Admin Guide for archiving the program measurement data for 2016-2017, but do not see the option to import the AcademicYearTemplate.csv.  (See screenshots attached).
[Archiving Prior Year - Importing Academic Year Screen Captures_v1.docx](https://github.com/smiths/MEASURE/files/1908617/Archiving.Prior.Year.-.Importing.Academic.Year.Screen.Captures_v1.docx)

Per the Admin Guide, I checked the Status Tracker and executed a Force Check-In because the Rubric Input Template and Course Report.xlsm files were checked out (See screenshots attached).
[Archiving Prior Year - Force Check-In-Screen Captures_v1.docx](https://github.com/smiths/MEASURE/files/1908616/Archiving.Prior.Year.-.Force.Check-In-Screen.Captures_v1.docx)

Do we know if the process for importing the AcademicYearTemplate.csv has changed?

Thanks,
Andrew

**Comment by arana2** [comment]
Closed - Looks like the Label "Template" replaced the word "Import"

**Comment by smiths** [comment]
@arana2 were you able to complete the archiving?  Do we need to update the Admin manual?

**Comment by arana2** [comment]
Yes, I was able to complete the archiving.  
[Archiving Prior Year - Screen Captures.docx](https://github.com/smiths/MEASURE/files/1908688/Archiving.Prior.Year.-.Screen.Captures.docx)

I think we should update the screenshots that still refers to the "Imports" button and change it with "Templates.
