### ISSUE TITLE
Archive 2016-2017

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#119]
The closing of issue #118 implies that this has been sorted out, but it would be good to have a record of the status of this issue here.  If the archive seems to have worked, then we can proceed with the next issue.  (I'll be creating an issue for rolling over to the next academic year shortly.)  If we need to update the documentation in the Admin guide, then we should do that.

@arana2, it is great to see that you added images to the last post.  The doc format attachments have to be downloaded to be viewed, but other formats (like png) show up on the html rendering.

**Comment by arana2** [comment]
Correct #118 is closed and successfully archived 2016-2017.

I will assign myself a separate task to update the Guides that still refer to "Import" instead of "Templates".

> @arana2, it is great to see that you added images to the last post. The doc format attachments have to be downloaded to be viewed, but other formats (like png) show up on the html rendering.

I'll remember this going forward.

Thanks,
Andrew

**Comment by smiths** [comment]
Yes, great idea to assign yourself an issue to update the documentation to use the proper terminology.  Do you need any help getting started with Git?  I have resources that I share with my undergraduate students that I could send to you?  You will want to:

1. Clone the repo (git clone)
2. Pull the recent version (there won't likely be any changes for a fresh clone) (git pull)
3. Modify your AdminGuide.docx file 
4. Add the file (git add)
5. Commit the changes locally (git commit)
6. Push the changes to our shared repo (git push)

If there are any questions, do not hesitate to ask.

**Comment by arana2** [comment]
As mentioned in #120, Historical Program Measurement Archive: Step 2 of 6: SQL Transformation is still waiting:
![image](https://user-images.githubusercontent.com/38359810/38756930-227407a0-3f39-11e8-8baf-22280fe92e25.png)

**Comment by smiths** [comment]
@arana2, my guess is that the changes that the Vena consultants made as the project progressed broke this functionality.  It was working when each instructor was specifically assigned a course, but then they changed things so that everyone could open everything.

I do not have any idea how to fix this.  Can you please create a ticket to vena support, using the e-mail address that I sent you.  Please CC me on the e-mail message.  We can also bring this up when we have our first phone conversation with the Vena people.

**Comment by arana2** [comment]
Submitted Issue: Vena Ticket 21467

**Comment by smiths** [comment]
@arana2, it is disappointing that the first thing we tried didn't work.  😒 The comments in the ticket response do not make sense to me.  I have never heard of Obero or Delbridge.  Maybe the consulting on this project was out sourced?  Regardless, we need to straighten this out with Vena.  I will contact Neetu and ask her to set up a meeting with us.

**Comment by smiths** [comment]
Yes, we will get it resolved.  This problem is definitely highlighting that we need someone in your role.  😄  Yes, I know Bogdan.  I thought he worked for Vena, but apparently he was subcontracting for them.  I'll send Bogdan an e-mail with a CC to you.  He has been off the project for years now, but maybe it is such a simple problem that he will be able to help?

I have no idea how to access the file that is being referenced.  The Vena files are not under version control, as far as I know.  I'm also not particularly optimistic that it will work.  I don't think the fault likes with the AcademicYearTemplate.csv file; it is a very simple file, after all.  I think it is the changes that happened to the rest of the infrastructure since the last time the archive was run.

**Comment by smiths** [comment]
@arana2, can you stop the hung job?  Is this something that is documented in the Vena User Guide?

**Comment by arana2** [comment]
I tried to locate the hung job, but the ETL Job History only keeps track of the latest 100 jobs.  Earliest Job available: 2018-04-16 00:10:07.
![image](https://user-images.githubusercontent.com/38359810/38828043-c7aabd72-4182-11e8-989d-a0bc2d258700.png)

Unfortunately, I cannot determine if the SQL Transformation job actually completed or is still pending.

I reviewed the Vena User Guide and did not find any references to stopping an ETL Job.  

I can try to create the New Academic Year (2017-2018) since creating a new year would detect if any of the archiving tasks are still running.

**Comment by smiths** [comment]
Yes, @arana2, I agree with the idea of trying to create the new academic year.  There isn't any harm in trying and the attempt will give us useful information.

**Comment by arana2** [comment]
I attempted to create a new Academic Year, but the SQL Transform job is still blocking us from proceeding.
![image](https://user-images.githubusercontent.com/38359810/38830136-4d6bf808-4189-11e8-8063-80564cb848b7.png)


I tried retrieving the JOB ID from the history, but found 0 matching records.  It may have been automatically archived.
![image](https://user-images.githubusercontent.com/38359810/38830191-776a6b94-4189-11e8-88af-5772f6719ff6.png)

As for next steps, I'll keep reviewing the documentation to see if there's anything that can help us understand why the SQL Transform job is frozen and if there's a way to stop the archiving process altogether.

**Comment by smiths** [comment]
Thank you for the update @arana2.  Too bad.  😒 I'm sure you are already doing this, but you should also spend some time reviewing the documentation on MEASURE.  It will save us time on Wednesday if you have a feel for what the software is supposed to do.

**Comment by arana2** [comment]
@smiths  I was able to archive 2016-2017

Reference:
![image](https://user-images.githubusercontent.com/38359810/39484419-c787b15c-4d43-11e8-830e-dbeb19450cef.png)
![image](https://user-images.githubusercontent.com/38359810/39484423-cae3ec26-4d43-11e8-9c6b-77e021b8a4d5.png)
![image](https://user-images.githubusercontent.com/38359810/39484428-ce929566-4d43-11e8-989e-76dcd3169179.png)
![image](https://user-images.githubusercontent.com/38359810/39484437-d2c9b7ae-4d43-11e8-87a4-69fce5f67042.png)

**Comment by smiths** [comment]
Great to see this issue finally closed!  😄 I assume that you are now moving on to #120?
