### ISSUE TITLE
Add 2013-2014 Year

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#12]
Michelle, can you please follow the instructions in the user manual and add the 2013-2014 year to MEASURE 2.0.  I have a meeting with @bhancas tomorrow (Aug 26) and I'll let him know that we are planning to do this.  This will allow Joe and Sam to experiment further with the system.

**Comment by zhengm2** [comment]
Hi Spencer,

I followed the instruction manual but i was unable to locate the "AcademicYearTemplate.csv" file. Perhaps this is something you can ask @bhancas about if you have a chance?

Thank you,
Michelle

**Comment by smiths** [comment]
Hello Michelle.  The file was in the e-mail that I sent to you on July 29th.  I’ll attach it again for your convenience.


If you have any other problems, can you please post them as comments in GitHub.  This will help if we need to have further discussion with Bogdan, since it will let him review the entire history of communication on the issue.













_________________________________


Spencer Smith, PhD, PEng
Associate Professor
Department of Computing and Software
McMaster University


Tel: (905) 525-9140 X27929
Room: ITB/167
Web: http://www.cas.mcmaster.ca/~smiths
_________________________________












On Aug 26, 2016, at 9:06 AM, zhengm2 <notifications@github.com> wrote:


Hi Spencer,
I followed the instruction manual but i was unable to locate the "AcademicYearTemplate.csv" file. Perhaps this is something you can ask
@bhancas about if you have a chance?
Thank you,
Michelle
�
You are receiving this because you authored the thread.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.

**Comment by zhengm2** [comment]
Thank you Spencer. 2013-14 has now been added.

**Comment by smiths** [comment]
That is great news that you were able to add 2013-2014 Michelle!  Thank you.
