### ISSUE TITLE
Start New Academic Year

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#120]
Create the new academic year 2017-2018 by following the steps in Section 8 of the AdminGuide.  If there are any questions, or problems, please add comments below.   If there is a need to update the documentation, we should do that as we go along.

**Comment by arana2** [comment]
I attempted to start a New Academic Year, but received a pop-up stating the job could not be submitted.
![image](https://user-images.githubusercontent.com/38359810/38756615-2316f862-3f38-11e8-8eac-896b8c0eb166.png)

I referenced the Job number to the ETL Process and it looks like the Historical Program Measurement Archive is still waiting for Step 2 of 6 to complete: SQL Transformation.
![image](https://user-images.githubusercontent.com/38359810/38756754-8d620e3c-3f38-11e8-985b-c98bfcfd7182.png)

![image](https://user-images.githubusercontent.com/38359810/38756757-91634398-3f38-11e8-94c5-37582b7df060.png)

Is this job waiting for a manual action to be triggered by us?

**Comment by smiths** [comment]
I think we need to sort out the historical job first.  I do not know how to do it, but by submitting a ticket we will hopefully get an answer.  While you are waiting for an answer, you might investigate a way to cancel the historical program measurement archive job.  I do not know how to cancel jobs, but you might be able to find something on google.  I will also send you the most recent version of the Vena user's guide that I have.

**Comment by arana2** [comment]
@smiths - I am able to create the new academic year (2017-2018)

Below are some screenshots:
1.  Create New Academic Year
![image](https://user-images.githubusercontent.com/38359810/39488964-fd7cc460-4d51-11e8-9139-7e0d3a52f1b1.png)

2.  Execute New Academic Year Template
![image](https://user-images.githubusercontent.com/38359810/39488971-03a1d286-4d52-11e8-81f4-a61211ed8047.png)

3.  Status at 2:47PM
![image](https://user-images.githubusercontent.com/38359810/39488981-0c057ea0-4d52-11e8-9d40-d79492c1dfb6.png)

![image](https://user-images.githubusercontent.com/38359810/39488997-168e7912-4d52-11e8-86eb-837815d9f4a0.png)

![image](https://user-images.githubusercontent.com/38359810/39488990-113acef2-4d52-11e8-8175-f8b68ed457d8.png)

![image](https://user-images.githubusercontent.com/38359810/39489004-1c18a8b2-4d52-11e8-8c95-3a5012598672.png)

![image](https://user-images.githubusercontent.com/38359810/39489009-1ef620dc-4d52-11e8-8cf5-7a599f6c790c.png)

4.  Output
![image](https://user-images.githubusercontent.com/38359810/39489018-26865916-4d52-11e8-99a9-d6cbe9c5e1a1.png)

**Comment by smiths** [comment]
Great!
