### ISSUE TITLE
Update Curriculum

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#121]
Once #120 is complete, we need to update the program and course data in MEASURE.  This is discussed in the DeptGuide.  We need to look at the curriculum already in MEASURE and make changes so that it matches the current curriculum.

The authoritative listing for the programs and their courses is given in the undergraduate calendar.  For instance, for Engineering 1 the courses are listed at:

http://academiccalendars.romcmaster.ca/preview_program.php?catoid=24&poid=14324&returnto=4569

A similar web-page exists for every program.  (Engineering 1 is actually common to all engineering degrees, except for the Integrated Biomedical Engineering and Health Sciences (IBEHS) program.)

As an example, the details for Chemical Engineering can be found at:

http://academiccalendars.romcmaster.ca/preview_program.php?catoid=24&poid=14050&returnto=4569

We need to go through each program and make sure that the courses in MEASURE match.  The Dept Guide shows how to add courses, move courses etc.  You can start trying to do this now, or we can wait until our next meeting.

**Comment by arana2** [comment]
Hi @smiths ,

I added the following courses provided by Maria:
![image](https://user-images.githubusercontent.com/38359810/40021986-a4dff5f0-5794-11e8-9454-68c286d7a9f3.png)

We may need to add the courses to the other programs, but shouldn't be an issue to do.

This is actually a two step process:
1.  Add the courses in Vena (Modeler -> Members ->Programs
2.  Update the rubric input template (CourseList tab - which is a hidden tab) with the new courses

![image](https://user-images.githubusercontent.com/38359810/40022327-9e15a73c-5795-11e8-9a03-b28a534fd35c.png)

**Results:**
Rubric Input Template: 
![image](https://user-images.githubusercontent.com/38359810/40022427-fb8d1efe-5795-11e8-8fd1-894dbb7f3812.png)

![image](https://user-images.githubusercontent.com/38359810/40022406-eaece476-5795-11e8-8f14-61620283a09d.png)

**Comment by smiths** [comment]
Great!
