### ISSUE TITLE
Add Mac computer support for Course Reports

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#122]
The Rubric template works for Macs, but the Course Report does not.  We should investigate the following Vena proposal to fix this problem:

"We believe that this template was initially created on a Windows machine as they're compatible with ActiveX control (the macro-activation button) however Mac on Excel isn't compatible with them. It will work however if the you change it to a Form control.  This guide can help you with from controls under the section Add a button (Form control). | We believe that this template was initially created on a Windows machine as they're compatible with ActiveX control (the macro-activation button) however Mac on Excel isn't compatible with them. It will work however if the you change it to a Form control.  This guide can help you with from controls under the section Add a button (Form control)."

**Comment by arana2** [comment]
The Course Report has been updated to be compatible with Windows and Mac based machines.  Closing this ticket.
