### ISSUE TITLE
Document Steps for Mac Users

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#123]
If we can get the Mac support working for the Course Reports (issue #122) we will need to record the necessary technology for Mac users.  The minimum requirements for Mac users are:

1. Excel 2016 (McMaster users all have a site license)
2. Google Chrome

I'll send you an e-mail with the instructions for Vena, since I am not sure that I can put them on a public repo.

**Comment by arana2** [comment]
Hi @smiths ,

I believe the quick instructions guide for mac users covered this request.  
https://www.eng.mcmaster.ca/sites/default/files/quick_instructions_mac_v1.01.pdf

May we close this ticket?

**Comment by smiths** [comment]
Yes!
