### ISSUE TITLE
Test Course Report MAC on Windows

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#129]
Similar to issue #128, but on a Windows machine.

**Comment by arana2** [comment]
Hi @smiths ,

I would like to recreate the Summary and Detail Charts, that was outputted for Vena.  Can you provide the Program, Year, and Section used:

![image](https://user-images.githubusercontent.com/38359810/39372013-460653fc-4a11-11e8-93b5-7df83ca4f06b.png)

**Comment by smiths** [comment]
@arana2, I do not know what data has been entered, if any for MECH ENG 4K03.  The data currently in the MEASURE database is far from complete.  There was a fairly big push to add data for the 2016-2017 year, so I would focus on that year.  However, I do not know which term any given course was offered in, so you would need to check both terms, or look at the undergraduate calendar.

To get more information on which rubrics have been started (and are thus likely to have been completed), you can look at the Rubric Entry Report (described on page 24 of the Department Guide).

The Valid Course Information Template (described on page 22 of the Department Guide) lists the courses and the term in which they are offered.

**Comment by arana2** [comment]
Thanks @smiths 
Below are some screenshots using the following data:
Course: SFWR ENG 2AA4 (Software Design I - Introduction to Software Development)
Term: 2016 - 2017 Term 2
Section: 1

**Overall feedback**: the MAC version of the Course Report seems to be working well from a functional perspective.  My only feedback is the title of the X axis for the specific attribute (i.e. 4 Design) it is showing up as the number 1.  Maybe we can look into changing that to a meaningful title in the future.

I think we can close this issue, but would like to know your thoughts.

Filename: 
![image](https://user-images.githubusercontent.com/38359810/39384801-f95f2bde-4a3b-11e8-8e55-06ca419abbb5.png)

Summary Table
![image](https://user-images.githubusercontent.com/38359810/39384791-f0d9dedc-4a3b-11e8-8fc2-01d87791e321.png)

4 Design
![image](https://user-images.githubusercontent.com/38359810/39384866-36cc0dfc-4a3c-11e8-8d05-51db8f3ad396.png)

![image](https://user-images.githubusercontent.com/38359810/39385015-beaaad0a-4a3c-11e8-9711-655c011def8a.png)

**Comment by arana2** [comment]
This warning message is not impacting the presentation of the charts in Excel.  The data is correctly being retrieved and calculated to populate the chart.

I think we can close this ticket.

**Comment by smiths** [comment]
Yes, we might be pickier in the future, but the Warning message does not seem to be a problem at this time.  We can close this issue.
