### ISSUE TITLE
Please Test Rubric Report on a Mac

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#132]

**Comment by arana2** [comment]
Hi @smiths  - is this referring to the Rubric Entry Report?
Contributor -> Reports -> Rubric Entry Report.xlsx

![image](https://user-images.githubusercontent.com/38359810/40074051-936bd192-5846-11e8-974e-873c6d5a1e07.png)

**Comment by smiths** [comment]
No, it was referring to the Rubric Input Template.  I believe we have adequately tested the Rubric Input Template.  We can close this issue.
