### ISSUE TITLE
How to update Course Report Template to use Course Report Mac?

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#133]
We want the option of using the Course Report Mac in the Contributor view.  It seems like this could be done with a simple renaming.  Please follow up with Minh.

**Comment by arana2** [comment]
Followed up with Minh.  I will update this issue when we get a response.

**Comment by smiths** [comment]
Sounds good.

**Comment by arana2** [comment]
The Course Report has been updated and can now be used by Mac and Windows based machines.  Closing the ticket.
