### ISSUE TITLE
2017-2018 Rollover to Rubric Input Template Incorrect for SFWR ENG 2AA4

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#137]
The Rubric Input Template for the 2017-2018 version of SFWR ENG 2AA4, Term 2, has the learning outcome text as "Is aware of the PEO and the role of licensing" for all learning outcomes.  The text was expected to match the descriptions from the learning outcomes in the 2016-2017 version.  The rollover to the new year seems to have failed in this respect.  It is like all of the previous text was replaced by the text from the last learning outcome.  I'll attach a screen shot below.

![newyearproblem](https://user-images.githubusercontent.com/1422000/39663964-f1fd8548-5049-11e8-89a3-d600e0ace4b7.png)

After further investigation, the problem was worse than originally noted.  Not all of the indicator rows showed up and adding rows did not work.  To enter the rubric, I had to use the manager view.  It was not possible from the contributor view.  Hopefully the problem is limited to the 2aa4 entry, and not all courses.

The manager view of 2aa4 and the contributor view are currently different.  There is something weird going on behind the scenes here.  Again, this is hopefully limited to the 2AA4 course.

**Comment by arana2** [comment]
Hi @smiths ,
I believe this issue has been resolved by Minh already.  The Rubric Input Template has been updated and the repeating learning outcome text has been corrected.

May we close this issue?

**Comment by smiths** [comment]
Yes.  This problem has been fixed.
