### ISSUE TITLE
2017-2018 Rollover to Rubric Input Template Incorrect for SFWR ENG 3GB3

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#138]
Unfortunately the issues for SFWR ENG 2AA4 #137 are repeated for other courses.  Testing with SFWR ENG 3GB3 (Term 2) led to the same problems.  Since I already knew what problem to expect, I looked at SFWR ENG 3GB3 more systematically than 2AA4.  I'm almost certain that the problem is related to copying line items from one year to the next.  In the rollover there are fewer line items than expected and they are mostly mislabelled.

The data for 2016-2017 show the line items (learning outcomes) that were expected.

![se3gb3_2016_2017](https://user-images.githubusercontent.com/1422000/39666893-f38d0eea-5078-11e8-9190-765d2dbcd4ef.png)

The 2017-2018 version that came up when checking out the rubric is as follows.

![se3gb3_2017_2018](https://user-images.githubusercontent.com/1422000/39666896-10205a1c-5079-11e8-81dd-a52403a1bd0f.png)

From my previous experience with 2AA4 (issue #137) I suspected that the line items were tied together.  When I deleted one line item (the last one), they were all removed.

![se3gb3_2017_2018_afterremovelastline](https://user-images.githubusercontent.com/1422000/39666906-2d178078-5079-11e8-82e1-8152c4af6b4e.png)

I then worked with the rubric to re-add the line items and the data for the current year.  In the Manager view of the template, I see exactly what I entered.  In the contributor view I see the line items repeated.  I have no idea why the two views are different.  The 2AA4 rubric also looks different depending on whether it is accessed through the manager or contributor view.

**Comment by arana2** [comment]
Hi @smiths ,

For SFWR ENG 3GB3, I compared the data between 16-17 vs 17-18
- Looks like we entered the data already for Jacques Carette on 5/11/17
- The order is fine and there are no repeating rows as mentioned in the issue

Attached are screenshots for reference:
**2016-2017**
![image](https://user-images.githubusercontent.com/38359810/40859600-5d68a7f6-65b0-11e8-9f62-cfc06b510c54.png)

**2017-2018**
![image](https://user-images.githubusercontent.com/38359810/40859623-73d9ea2c-65b0-11e8-8655-43717a4a9bfa.png)

**Comment by smiths** [comment]
We can close this issue.  I actually thought we already had.  😄
