### ISSUE TITLE
Chem Eng 3E04 (term 1) - Unable to Access the Report 

### ISSUE THREAD

**Issue by arana2** [smiths/MEASURE#139]
Per Alba B.'s test results"
**Course with Attributes/Indicators Removed:**
Testing 3E04, I saw that there was an error where I am not able to access the report because I am supposedly selecting the wrong term or that the report does not exist for that year. "

![image](https://user-images.githubusercontent.com/38359810/39704577-c383f288-51d9-11e8-96a7-7d7259f173da.png)

**Comment by arana2** [comment]
@smiths 
- Academic Year has been rolled over to 2017-2018 Term 2
- I think this error is occurring because we started the academic year 2017/2018 at Term 2

**Comment by arana2** [comment]
Per Farhad M's notes, Farhad was able to update the "Measured indicators" and "Rubric input template" for:

- MECH ENG 4T03 (2017-2018 Term 1)
- MECH ENG 4V03 (2017-2018 Term 1)
- MECH ENG 3O04 (2017-2018 Term 1)
- MECH ENG 2A03 (2017-2018 Term 1)
- MECH ENG 2P04 (2017-2018 Term 1)
- MECH ENG 3F04 (2017-2018 Term 1)
- MECH ENG 4Q03 (2017-2018 Term 1)

**Comment by arana2** [comment]
Followed up with Alba to ensure her course data is entered for Chem Eng 3E04 (term 1)

**Comment by smiths** [comment]
@arana2, good idea to follow up with Alba.  There is a chance that Alba isn't involved in the project anymore.  Chemical Engineering seemed to have a finite duration employment contract, but that could have been extended.

**Comment by arana2** [comment]
@smiths Alba has successfully entered the rubric data for CHEM ENG 3E04.

I reviewed the Rubric Input Template and Course Report for CHEM ENG 3E04 and did not find any inconsistencies or errors.

May we close this ticket?

**Comment by smiths** [comment]
Great news!  Yes, please close the ticket.
