### ISSUE TITLE
Term 3 in current year should not show a warning

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#140]
Term 3 courses in the current year, Term 2, show a warning for rubric data entry, because Term 3 is not considered the current term.  Term 3 should not show a warning though because Term 3 course data is entered in Term 2.  As an example SFWR ENG 4GP6 shows a red warning.

This isn't a high priority, but I wanted to make a note of it when I noticed.  😄

**Comment by arana2** [comment]
Hello @smiths ,
This enhancement has been delivered.  I updated the Excel conditional statement and also added SFWR ENG 4GP6 to the CourseList tab (hidden).

The updated version can be found in the Files Library-->Input Forms: **Rubric Input Template-Testing.xlsm**

If we are okay with this solution, I can replace the current Rubric Input Template with the updated version.

Test Plan
1.  Open SFWR ENG 4GP6 for 2017-2018 Term 3
Expected Results: Do not show warning Message
Actual Results: Do not show warning Message
**Pass**
![image](https://user-images.githubusercontent.com/38359810/40002741-9a4850b8-575f-11e8-813b-acffb8d941f5.png)

2.  Open 2AA4 for 2017-2018 Term 2
Expected Results: Do not show warning Message
Actual Results: Do not show warning Message
**Pass**
![image](https://user-images.githubusercontent.com/38359810/40002806-bdf7ec6c-575f-11e8-8671-1b439cce983a.png)

3.  Open Open 2AA4 for 2017-2018 Term 1
Expected Results: Show warning Message
Actual Results: Show warning Message
**Pass**
![image](https://user-images.githubusercontent.com/38359810/40002862-e27f3888-575f-11e8-8772-19a65e037703.png)

**Comment by smiths** [comment]
Great to see you already  using your Vena knowledge.  I think we can close this issue.

**Comment by arana2** [comment]
Excellent.  I migrated the updated rubric input template and kept a copy of the previous version.
