### ISSUE TITLE
SFWR ENG 3I03, Term 2, 2016-2017 versus 2017-2018

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#141]
The roll over to 2017-2018 is incorrect for SFWR ENG 3I03 (Term 2).  As for issue #137 and #138 learning outcomes are incorrectly repeated and many learning outcomes are missing.

The 2016-2017 version of SFWR ENG 3I03, Term 2 looks like this:

![3i03_2016-2017](https://user-images.githubusercontent.com/1422000/39709448-d9e558c4-51e7-11e8-98cb-f3c63589871a.png)

The 2017-2018 version looks like this:

![3i03_2017-2018](https://user-images.githubusercontent.com/1422000/39709455-e54a421a-51e7-11e8-827c-8d19a4be3b9a.png)

**Comment by arana2** [comment]
- The SQL fix to save the order of the LID's has been implemented and will be in effect for the new year

- The order of the LID's prior to the fix will remain since the SQL fix can only be executed when a new year is created
