### ISSUE TITLE
SFWR ENG 2GA3, Term 1, 2017-2018 does not match 2016-2017

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#142]
![2ga3_term1_2016_2017](https://user-images.githubusercontent.com/1422000/39709742-b86551ee-51e8-11e8-9be4-fa57303c9fa3.png)

VERSUS

![2ga3_term1_2017_2018](https://user-images.githubusercontent.com/1422000/39709762-bdd62090-51e8-11e8-8987-918c7f45e643.png)

**Comment by arana2** [comment]
Hi @smiths ,

I reviewed the two templates under the Contributor view for both Windows and MacOS based systems and did not find any errors.

**Testing Criteria**
- Look for repeating rows
- Ensure the order of the line items remain the same
- For 2017-2018, the "Measurement Date" and "Number" was cleared
- The cells that do not require user input remain protected

****Test#1** - Test the SFWR ENG 2GA3 2016-2017 template vs 2017-2018 template**
Operating System: Windows 10
Browser: Google Chrome
View: Contributor

****Test#2** - Test the SFWR ENG 2GA3 2016-2017 template vs 2017-2018 template**
Operating System: MacOS - High Sierra 10.13.4
Browser: Google Chrome
View: Contributor

Would we happen to have course data to enter for the 2017-2018 term?

I've attached the templates I used to test the defect
1.  SFWR ENG 2GA3_2016-2017
2.  SFWR ENG 2GA3_2017-2018 (this template was used to compare against the 2016-2017 template to test for errors, repeating rows and order of line items)
3.  SFWR ENG 2GA3_2017-2018_MAC (this template was used to compare against the 2016-2017 template to test for errors, repeating rows and order of line items)

[SFWR ENG 2GA3.zip](https://github.com/smiths/MEASURE/files/2036947/SFWR.ENG.2GA3.zip)

**Comment by smiths** [comment]
Glad to see that this problem has been fixed.  The problem was how Vena previously did the roll over to a new academic year.  Unfortunately, I do not have the data for 2017-2018.  This isn't a course that I teach.  I don't actually know who taught it this year, although if you need to know, the information is probably on the CAS web-page somewhere.

I'm going to close this issue, since the problem is now (hopefully) behind us.
