### ISSUE TITLE
Civ Eng 3K03, Term 1, 2016-2017 versus 2017-2018

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#143]
These two examples seem to be consistent, and possibly correct.  The order of the line items has changed, but they appear to all be there, and I don't see duplication.

![civeng3k03_term1_2016_2017](https://user-images.githubusercontent.com/1422000/39710144-f509c462-51e9-11e8-8f74-6149408b0d36.png)

![civeng3k03_term1_2017_2018](https://user-images.githubusercontent.com/1422000/39710147-f7d3fbae-51e9-11e8-98eb-cb6485012759.png)

**Comment by arana2** [comment]
- July 16, 2018 - Neetu asked Minh to review 
- August 2, 2018 - Followed up on the status
- #141 is the same issue

**Comment by arana2** [comment]
- The SQL fix to save the order of the LID's has been implemented and will be in effect for the new year

- The order of the LID's prior to the fix will remain since the SQL fix can only be executed when a new year is created

**Comment by smiths** [comment]
Great news!
