### ISSUE TITLE
Rubric Input Template - Clearing the Comments / Assumptions Cell Values for the New Academic Year

### ISSUE THREAD

**Issue by arana2** [smiths/MEASURE#144]
When a new academic year is created, the values in the Comments / Assumptions column should also 
be empty for an existing course.

This will ensure comments from a prior year are not accidentally left on for an indicator/learning outcome.

**Example**
**2017-2018**
Rubric Input Template containing comments for 2017-2018
![image](https://user-images.githubusercontent.com/38359810/39763842-33ab4ec6-52ac-11e8-9426-c9c59e7d4912.png)

**2018-2019**
Comments from 2017-2018 should be removed when opening the rubric input template for 2018-2019
![image](https://user-images.githubusercontent.com/38359810/39763763-fdce1694-52ab-11e8-86e7-786a2e4c2cbb.png)

**Comment by smiths** [comment]
Thank you @arana2.  I'm actually not 100% convinced that this is the right course of action.  I personally like having the comment, since it reminds me of the kind of things I said the previous year.  I can see this either way.  Now that we have the issue, we'll be sure to return to this question.  We can ask a few stakeholders in the future and find out exactly what most people want.

**Comment by arana2** [comment]
- Based on the latest feedback, some of the users prefer not to have Comments/Assumptions values to be rolled over to the new year
-  Reason: preserving comments might lead to outdated comments being overlooked upon entry of new numbers
-  @arana2 will assess the request and determine if Vena Support is required

**Comment by arana2** [comment]
- Opened a Vena Support Ticket for this request:  https://support.venasolutions.com/hc/en-us/requests/31462
- From my understanding, a stored procedure in Vena's internal SQL Server requires to be updated (which I don't have access to)

**Comment by arana2** [comment]
- Vena Support updated the SQL stored procedure to stop the comments/assumptions value from rolling over to the new year
- Closing the ticket, but will add a reminder to check the comments/assumptions cell when rolling over to the new year
