### ISSUE TITLE
Fix order of learning outcomes (line items) in new year

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#145]
Currently when a new year is generated (say rolling over from 2016-2017 to 2017-2018) the Rubric  Input Templates have the order of the learning outcomes (line items) changed, unless there is only one line item under an indicator.  This could be potentially confusing to instructors, since they may have picked a particular order.  Mechanical engineering in particular likes to label their learning outcomes as Topic 1, Topic 2, etc.  If the order is shuffled this is confusing.

**Comment by arana2** [comment]
This was brought up with Minh during the training.  Unfortunately, this is existing functionality and Vena is pulling the data in the order it retrieves it.  I labeled this as Vena 3.0 as we may need to have a design discussion on how we want the learning outcome is displayed when retrieved.

**Comment by smiths** [comment]
Good to know that you discussed it with Minh.  Good idea to change the label.  We could probably sort the learning outcomes alphabetically, that way they would be in the same order if they weren't changed.  Actually, that doesn't work, unless the first time they are entered the user sorts them alphabetically.  Maybe there is a way to insert some kind of tag or comment that we can sort on?  Anyway, this is something we can think about once we get Vena 2.0 up and running.  😄

**Comment by arana2** [comment]
- Closing issue
- The SQL fix to save the order of the LID's has been implemented and will be in effect for the new year
- The order of the LID's prior to the fix will remain since the SQL fix can only be executed when a new year is created
- Reference #207
