### ISSUE TITLE
McMaster <> Vena Deployment Plan

### ISSUE THREAD

**Issue by arana2** [smiths/MEASURE#146]
- [x] Minh to remove 2017-2018 and 2018-2019 and recreate a fresh 2017-2018.

- [x] Re-enter data for courses, test functionality with Windows.  We need to tell Farhad and Alba when this is available for them.

- [x] Test Mac templates, decide whether to switch to this template going forward.  Spencer and Andrew should be able to test.

- [x] Training with Minh for Andrew and Sinisa, build confidence in MEASURE, create reports as described in Spencer’s email to Ashley on April 24 

- [x] Officially make Vena available for rubric and course report entry on Monday, May 14

**Comment by smiths** [comment]
Looks great.  Thank you @arana2.

**Comment by arana2** [comment]
for the new CEAB Report, Minh and I begin developing the new report.  Still a work in progress. #116

**Comment by smiths** [comment]
@arana2, Farhad and Alba have successfully tested the Rubric Input Template.  I sent an e-mail to them today (May 14) for them to check the Course Report Template.  In the future we should think about just one input template and one report template.

**Comment by arana2** [comment]
Thanks @smiths 
That's a good idea.  

Possibly a single input template with multiple spreadsheets.  Same applies for a single report template with multiple spreadsheets.

**Comment by arana2** [comment]
Tested the Rubric Input Template and Course Report Template with the Mac

**Comment by arana2** [comment]
We made Vena available for rubric and course report entry on Friday May 18, 2018.
