### ISSUE TITLE
Current Year in Measure is showing 2016-2017 Term 2

### ISSUE THREAD

**Issue by arana2** [smiths/MEASURE#147]
I noticed this warning message was being displayed in the rubric input template

The current year in MEASURE is 2016-2017 Term 2
![image](https://user-images.githubusercontent.com/38359810/39946840-c929e186-553d-11e8-8cbf-12257027b3c4.png)

It should be 2017-2018 Term 2

**Comment by smiths** [comment]
Yes, I mentioned this in an e-mail to @arana2 on May 10, but I really should have created an issue.  Sorry.

Please update the year and term to 2017-2018, Term 2.

**Comment by arana2** [comment]
The current term has been updated to 2017-2018 Term 2.  Warning message is no longer appearing when entering course data for 2017-2018 Term 2.

Test Plan
1.  Open template for 2016-2017 (Term 2)
Expected Results: Display warning message
Actual Results: Display warning message
**Pass**
![image](https://user-images.githubusercontent.com/38359810/40001526-5ecd7d7c-575c-11e8-9072-3049ee0507d6.png)

2.  Open template for 2017-2018 (Term 2)
Expected Results: Display warning message
Actual Results: Display warning message
**Pass**
![image](https://user-images.githubusercontent.com/38359810/40001586-8820e38a-575c-11e8-9291-cbe69a1e985f.png)

**Comment by smiths** [comment]
Great!
