### ISSUE TITLE
Rubric Entry Report Year?

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#148]
@arana2, was there a change with the Rubric Entry Report?  I tried to look at the courses entered for 2017-2018 and I can no longer select any years other than 2013-2014 and 2014-2015?  Could we open it up again so that we can select any year?

![untitled](https://user-images.githubusercontent.com/1422000/40015712-37c37116-5782-11e8-8e64-d384f9ab495c.png)

On a related point, the only Programs I can select for the Rubric Entry Report are Chemical Engineering programs.

**Comment by arana2** [comment]
Hi @smiths ,

I don't recall any changes being made to the Rubric Entry Report.  How are you opening the file?

I created a copy in Manager -> Files Library -> **Rubric Entry Report - Testing. xlsx**

and looks to be working as expected:

Program Selection:
![image](https://user-images.githubusercontent.com/38359810/40020482-2e35b768-5790-11e8-8365-8ea2255ff71a.png)

Year Selection:
![image](https://user-images.githubusercontent.com/38359810/40020553-5786ae56-5790-11e8-8ecb-0b37352b2f2f.png)


Results:
![image](https://user-images.githubusercontent.com/38359810/40020572-67f45e78-5790-11e8-969e-9ad901c25ca4.png)
![image](https://user-images.githubusercontent.com/38359810/40020594-72236920-5790-11e8-9baf-4bbf208b2920.png)

**Comment by arana2** [comment]
I also tried the Contributor's Rubric Entry Report and seems to be working as expected.

Program Selection:
![image](https://user-images.githubusercontent.com/38359810/40021082-e2885e7c-5791-11e8-8c61-933186681a9e.png)

Year Selection
![image](https://user-images.githubusercontent.com/38359810/40021127-030c7b06-5792-11e8-98cd-798feb68da31.png)

Results:
![image](https://user-images.githubusercontent.com/38359810/40021157-1182c168-5792-11e8-921e-9f9e59a82007.png)
![image](https://user-images.githubusercontent.com/38359810/40021187-22a248f6-5792-11e8-97e0-b31eba3d6e7e.png)

**Comment by smiths** [comment]
My mistake.  I forgot that the Rubric Entry Report was not set-up to work on Macs.  I have been enjoying not needing to start a VM, but for the Rubric Entry Report, a Windows machine is necessary.  I'll close this issue.  I thought about creating an issue for updating the Rubric Entry Report to work on Macs, but I might be the only person that cares, so this is a low priority.

**Comment by arana2** [comment]
Thanks @smiths .  I've added this as  a system requirement for Accreditation 3.0.
