### ISSUE TITLE
Test Archive Previous Year

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#15]
Hello Michelle.  Could you please use the Admin Guide instructions to archive the 2014-2015 year.  You can test whether the archive was successful by looking at the Historical Program Measurement Report.  If you have any questions or concerns, or feedback, please post it as a comment below.

**Comment by zhengm2** [comment]
Hi Spencer. It looks like it was archived properly. 

In the admin guide under Item #5: Historical Program Measurement Archive step 4, the image needs to be updated.

**Comment by smiths** [comment]
Thank  you for testing this Michelle.  I have asked Evan to make some major changes to the documentation.  After he has finished, I'll send the documents to you for comment again.  At that time, please check whether the image has been updated.
