### ISSUE TITLE
Update Getting Started Documentation

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#150]
@arana2, we don't have time to update all of the documentation, but a quick start guide for Windows Users and Mac users would be good.  The focus would just be on entering the Rubric Input Template and the Course Report template.  We wouldn't want the instructions to be more than a page for each OS, since nobody will read a longer document. 

Do you think you could prepare something like this?  You could prepare it within this repo, and when it is done, we could port it over to the web-page?  We are waiting now for Farhad's feedback tomorrow (May 16), so are new projection for going live would be Thursday,  May 17.  Would it be feasible to have the quick start instructions by then?

**Comment by arana2** [comment]
1 - Guide for Windows Users
      - Rubric Input Template
      - Course Report
1 - Guide for Mac Users
      - Rubric Input Template
      - Course Report

Thursday May 17 should be fine.  I apologize for the delay in the responses - I've been in and out of the office support client issues

**Comment by arana2** [comment]
That works with me. We can address any questions/comments on a ad-hoc basis.

I have Minh's direct line in case we come across any roadblocks :)

**Comment by smiths** [comment]
Good to know, although we should verify with Minh the cost of his assistance.  For any new work, which isn't categorized as cleaning up previous work, there will be a charge from Vena going forward.  Hopefully we don't need too much new work.  😄

**Comment by arana2** [comment]
@smiths good to know :)

I've also shared the Quick Instructions Guide.  If we are aligned with the content and format, we can upload it to the MEASURE website.

**Comment by smiths** [comment]
I will review the instructions soon.  Thank you for preparing them.

**Comment by arana2** [comment]
Thanks @smiths 
May we close this ticket?
The documents have been created and uploaded to the MEASURE website.

**Comment by smiths** [comment]
Yes!
