### ISSUE TITLE
One input template for instructors

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#151]
When it is time to design Vena 3.0, we should consider just having one template for instructors to enter their data, as briefly discussed under #146.  Maybe we could have one input template with multiple spreadsheets?  Simpler is better for instructors.  Once the data entry period is over, we should have a brainstorming session with the users.

I've created a label Vena3.0 to track any ideas we have for the next version of Vena.  I've assigned this to @arana2 because all issues should have an owner, but there is nothing to do with this right now.

**Comment by arana2** [comment]
I've added this as a system requirement for Accreditation 3.0.

**Comment by arana2** [comment]
-  This request has been fulfilled
-  "Summary of Actions to be Taken for Continous Improvement..." fields from the Course report has been moved to the rubric input template
- The Summary and Detail View Charts have been moved to the rubric input template
- Course Report (read-only) will remain available
