### ISSUE TITLE
Course Report - Multiple User Access

### ISSUE THREAD

**Issue by arana2** [smiths/MEASURE#152]
Confirm with Vena if we can have multiple users check out a single file.  For now, we can check every morning and perform a force check in to keep the file open.  

Sent email to Vena for confirmation

![image](https://user-images.githubusercontent.com/38359810/40133846-e684b146-590e-11e8-8ac3-8b2bad5ecc7a.png)

**Comment by arana2** [comment]
@smiths ,
Per Susan and Minh's instructions, I've updated the Course report to Concurrent Checkout.  Multiple users will now be able to check out the course report.

**Comment by smiths** [comment]
Great!
