### ISSUE TITLE
Rubric Input Template: Data Entry Issue - Nicola

### ISSUE THREAD

**Issue by arana2** [smiths/MEASURE#154]
**System Information**
- Operating System: macOS High Sierra 10.13.4
- Browser: Google Chrome Version 66.0.3359.181
- Microsoft Office Version: Office 365

**Course Information**
- Course: COE3DQ5
- Term: 2017-2018 Term 1
- Section: 1

**1.  The Live Rubric Template does not display the warning message, “Please be aware that you are not selecting the current year!  The current year in MEASURE is 2017-2018 Term 2.”
Instead, it shows a red box where the text use to be**
![image](https://user-images.githubusercontent.com/38359810/40493170-25ca744e-5f40-11e8-9484-58ba0ff99fba.png)

**2.  The Live Rubric Input Template is no longer protecting any of the cells**

**3.  The Live Rubric repeats all of the previously mentioned Learning Outcomes for COMP ENG 3DQ5**
![image](https://user-images.githubusercontent.com/38359810/40493049-ea4f2d1a-5f3f-11e8-98d6-6d3bc61bb28d.png)

**4.  In the Live Rubric Template, I am able to delete the original learning outcomes, but when I try to remove the repeating rows, error appears “Invalid row selected”**
![image](https://user-images.githubusercontent.com/38359810/40493120-0f9d7a68-5f40-11e8-9ad9-153d5582e723.png)

**Comment by arana2** [comment]
Vena Ticket:  venasupport.zendesk.com/hc/requests/22245

**Comment by arana2** [comment]
Nicola is satisfied with the issue resolved.

May we close this ticket?

**Comment by smiths** [comment]
Yes!
