### ISSUE TITLE
Section 2 in Vena are not active and the instructor cannot enter his measurement - Shahram

### ISSUE THREAD

**Issue by arana2** [smiths/MEASURE#155]
Per Shahram's issue,

"We had two sections of ELEC ENG 2CI5 in the fall term. I have been informed that the cells for section 2 in Vena are not active and the instructor cannot enter his measurement. I tried to activate them but cannot see the sections.
Your help is appreciated."

System Specs:
Office 2016.
Mac OS.
Safari.

**Comment by arana2** [comment]
Followed up with Shahram to see if they are still experiencing the issue

**Comment by arana2** [comment]
I provided ad-hoc training for Professor Bakr regarding this course.  He was satisfied with the training and did not have further questions when I brought this issue.

I think we can close this for now.

**Comment by smiths** [comment]
Agreed.
