### ISSUE TITLE
Opens ELECT ENG 2CI5, but receives a Robotics Course - Prof. Bakr via Shahram

### ISSUE THREAD

**Issue by arana2** [smiths/MEASURE#156]
"Every time I choose Elec Eng 2CI5 and I check out its file I end up getting the one for a Robotics course!  Is there any training or help session coming soon?"

Andrew was able to access ELEC ENG 2CI5 for both Windows and MacOS.  Sent follow up questions to Prof. Bakr for further information

**Windows (Google Chrome, Microsoft Office 2016)**
![windows](https://user-images.githubusercontent.com/38359810/40616407-eb909c24-6258-11e8-870b-5c851ab23397.jpg)

**MacOS (Google Chrome, Microsoft Office 2016)**
![mac](https://user-images.githubusercontent.com/38359810/40616415-f3a0ac06-6258-11e8-846e-202ecd073792.jpg)

**Comment by smiths** [comment]
My guess is this isn't a problem with Vena, but a user error.  I guess a training session will be needed.  In the mean time, you could point people with questions toward the documentation.  I also find that screenshots help.  You can often diagnose what they are doing wrong from a screenshot.

**Comment by arana2** [comment]
Will do!  Thanks @smiths

**Comment by arana2** [comment]
Met with Dr. Bakr today and provided him with personalized training session for using the rubric input template.  We added a line item, saved it, and retrieved it with no issues.

He is satisfied with the training and happy Vena is working as expected.

Closing this issue.

**Comment by smiths** [comment]
Excellent!  Did your training session with Dr. Bakr show any deficiencies in our documentation, or did he not really consult the documentation?

**Comment by arana2** [comment]
Hi @smiths ,

I almost missed this question.  Dr. Bakr did not really consult with the documentation provided.   I noticed this because when I asked him to show me how he accessed the templates, the "enable Macros" and "allow content" buttons that would appear in Excel were ignored.  

I showed him the "best practices" for checking out the template, opening the template, pressing the button for both "enable Macros" and "allow content", keying in data, saving, closing, and checking in the template.

He picked up the process quickly and re-did the steps to ensure we are aligned.

**Comment by smiths** [comment]
Thanks for the insight @arana2.  That is what I expected.  What you did is the best approach, in general.  If a user says something doesn't work, we need to see what steps that used to produce the problem, since often the error will be on their side and not on the software side.
