### ISSUE TITLE
Unable to Open Rubric Input Template for COE4DK4 - Terry

### ISSUE THREAD

**Issue by arana2** [smiths/MEASURE#157]
"I'm now stuck. When trying to checkout the rubric entry for coe4dk4 2017-2018 Term 1, I get an error message that "There is a problem sending the command to the program."

- Andrew manually checked Terry out of the file.
- Successfully accessed the rubric entry template for Windows
- Asked Terry to try accessing the template again.

**Comment by arana2** [comment]
User was able to fix this issue.

[https://windowsreport.com/there-was-a-problem-sending-command-program/](https://windowsreport.com/there-was-a-problem-sending-command-program/)

When hardware acceleration is disabled, the problem no longer appears.

This may be a result of Excel (Windows OS) is running as a VM with Linux as a host.

**Comment by smiths** [comment]
Can we close this issue?

**Comment by arana2** [comment]
Thanks @smiths .  Yes, we can close it.
