### ISSUE TITLE
COMP ENG 4DK4 - Uploading a PDF Error - Terry

### ISSUE THREAD

**Issue by arana2** [smiths/MEASURE#158]
@smiths 

When uploading a file via Vena Comment to COMP ENG 4DK4, we receive a network error.  However, I am able to succsesfully upload a file when testing another course: SFWR ENG 4GP6.  Sending an issue to Venasupport.

![image](https://user-images.githubusercontent.com/38359810/40617956-f52196f8-625d-11e8-8a9e-0f45d34fa1d7.png)

**COMP ENG 4DK4  - FAIL**
![image](https://user-images.githubusercontent.com/38359810/40617975-03b9465c-625e-11e8-8296-9b2be5eda5ab.png)

**SFWR ENG 4GP6 - SUCCESS**
![image](https://user-images.githubusercontent.com/38359810/40618031-2e2669d8-625e-11e8-8051-b33199fc82a4.png)

**Comment by arana2** [comment]
Reference:  https://venasupport.zendesk.com/hc/en-us/requests/22298

**Comment by smiths** [comment]
Strange.   I wonder if something was done in last year's version of the course data that didn't roll over well to this year's version?  I don't know if we ever tested the "roll over" of a template that had files attached as comments.

**Comment by arana2** [comment]
We cleaned up the data inside the template and fixed Terry's upload issue.

May we close this ticket?

**Comment by smiths** [comment]
Great work @arana2.  Yes, we should close this ticket.
