### ISSUE TITLE
Course Report - Error 400 [Windows Users] and System Error &H80070057 (-2147024809) [Mac Users]

### ISSUE THREAD

**Issue by arana2** [smiths/MEASURE#160]
When the Detail/Summary chart button is pressed, the error would appear and not load the charts.

**Comment by arana2** [comment]
RESOLVED

These error messages occurred because the VBA Code to update the charts were trying to execute while the sheets were protected.

Added VBA Code to protect the sheet by default.
Added VBA Code to un-protect the sheet when...
- the Detail/Summary chart button is pressed
- when the charts are being refreshed
Once the function is complete, the sheet will then be locked.

**Comment by smiths** [comment]
Good job diagnosing and fixing the problem.  Does that mean that you can close this issue?

**Comment by arana2** [comment]
Hi @smiths ,
Yes I just tested on both MAC and Windows and the error is no longer displaying.

**Comment by smiths** [comment]
Great!
