### ISSUE TITLE
Mac Users - Inserting a New LID

### ISSUE THREAD

**Issue by arana2** [smiths/MEASURE#162]
Shared with Jake from Vena

Some of our Mac users in contributor view is experiencing the following issue.

When the “Insert” button is pressed, the new LID row is created, but we are experiencing two issues.

Issue 1.  The loading icon continues to spin beside the Insert button
Issue 2.  This leaves the template unprotected and allow the user to modify the template if they wish.

Rubric Input Template
<img width="640" alt="capture" src="https://user-images.githubusercontent.com/38359810/40790458-fbed1978-64c2-11e8-80a5-1837ac4a4aeb.PNG">

**Comment by arana2** [comment]
5/31/18 - Vena Support confirmed issue.  Working on a fix.

**Comment by smiths** [comment]
Good to know and good to hear.

**Comment by arana2** [comment]
6/5/2018 - Vena response, The fix for this is scheduled to be in by next Friday (June 15th).

This may impact our training session for Mac users planned for the second week of June.  We may continue with the training session, but will have to notify Mac Users ahead of time that they may not be able to insert or delete rows.  

An unfavorable suggestion, I would wait until the Mac defect is resolved to allow our Mac users to follow along with the training session.  With Vena's current reputation, I am not sure if it would be a good idea to explain to our users that we still have some ongoing defects while training our users.

Let me know what you think.

**Comment by smiths** [comment]
Isn't there currently a work around for this issue?  It would be better if the user interface didn't hang, but disconnecting and reconnecting usually fixes it, doesn't it?  Assuming that we have this work around, I think we can proceed with the training, give the Mac users the advice to restart and tell them that we are working on removing the problem all together.

**Comment by arana2** [comment]
- Vena deployed a fix on July 26, 2018
- Executed 4 test cases where all 4 passed
**Test 1:** Insert additional LID and entering data in the new LID 
**Test 2:** Saving the template after inserting an LID, Closing Template, and Re-Opening the Template 
**Test 3:** Insert a new LID, Remove the same LID, insert another LID and enter data 
**Test 4:** Insert another LID in the same row where the last LID was removed, enter data, confirm only unprotected cells can have data entered, save template
- Attached test case document for reference
[Vena Test 22374.docx](https://github.com/smiths/MEASURE/files/2253926/Vena.Test.22374.docx)

Closing this ticket

**Comment by smiths** [comment]
Congratulations on closing this issue @arana2.  It was thanks to your persistence, and thorough testing, that we were able to be successful.

**Comment by arana2** [comment]
Thanks @smiths :)
