### ISSUE TITLE
Mac Users - Uploading a File as Comment

### ISSUE THREAD

**Issue by arana2** [smiths/MEASURE#163]
Hi @smiths ,

Today, Mac Users do not have the capability to upload a file as a Vena Comment.

This is currently impacting the following templates/reports where Mac users may need to upload a sample file:
- Rubric Input Template
- Course Report
- Curriculum Committee Recommendation Report

I had a chat with the Vena Support Team today and discuss work around and we though of two.  I would like to get your thoughts on both workarounds and see which approach works best.  Workaround 1 seems to be ideal for the interim.  

-	Workaround 1 – Interim Solution
-	If a Mac User has a file to upload in a template/report, they would contact their Department Administrator and have their admin upload their file for them as a comment (via Windows OS) 

-	Workaround 2 – Possible Long Term Solution
-	Create a workflow for each course and have Mac users upload their files as a comment via Vena website
-	Possibly consider this for V3.0

**Comment by smiths** [comment]
Thank you @arana2 for creating this issue.  I agree with your recommendation of Workaround 1.  The other workaround is something for us to consider in the future, but it isn't something to rush into.  Attaching courses to all of the Vena process workflow infrastructure will have benefits, but it will also be harder to maintain.  We would need to convince ourselves that the benefits would out-weight the effort.

No all users are interested in attaching files.  My understanding is that must users do not care.  The only time that the samples of student work are likely to be used are in an accreditation year, so we have time to make a plan.  We will also need to make sure that whatever we do fits with the needs of the accreditation visitors.  The current approach is probably not the right one from that point of view.

**Comment by arana2** [comment]
For tracking purposes, Vena Product Enhancement Ticket created:

https://support.venasolutions.com/hc/en-us/requests/26921

**Comment by arana2** [comment]
- macOS users now have the capability to comment or add/remove a file to a specific cell via Contributor Connector
- New feature will be added to the Instructor Guide

**Testing Information**
Course Name: TEST 103
Year: 2019-2020, Term 1
Section: 1
Tester: Andrew Aran
Date: April 5, 2019
Tenant: mcmasterdev2
Filename: Rubric Input Template WIP MAC.xlsm

**Add new comment / View comment**
![image](https://user-images.githubusercontent.com/38359810/55652317-27cfb200-57b9-11e9-8138-585c1d4902a5.png)

**Viewing all comments** 
![image](https://user-images.githubusercontent.com/38359810/55652371-4df55200-57b9-11e9-9574-aad568b1001a.png)

**Viewing a specific cell contaiing a comment**
![image](https://user-images.githubusercontent.com/38359810/55652440-77ae7900-57b9-11e9-8fc7-6064813d0e24.png)

**Downloading a file from a comment using macOS**
![image](https://user-images.githubusercontent.com/38359810/55652532-b2b0ac80-57b9-11e9-9d28-485885b768bb.png)

**Warning message before deleting a file/comment**
![image](https://user-images.githubusercontent.com/38359810/55652718-57cb8500-57ba-11e9-9431-9821f3535640.png)
