### ISSUE TITLE
Request to extract historical data for ECE Department - Shahram

### ISSUE THREAD

**Issue by arana2** [smiths/MEASURE#164]
As requested by Shahram, a meeting has been set up to gather more information and determine feasibilty

Meeting Date: Tuesday June 12 1130 AM -1200 PM
Location: ITB-A225

**Comment by smiths** [comment]
Great!  Good idea to put this in the issue tracker.

**Comment by arana2** [comment]
Request fulfilled.

Provided Shahram with a walkthrough on how to use the Historical Program Measurement Report to generate reports on the status of the program's year-to-year trend of the measured expectations.  Also showed him how to retrieve the historical program measurement by attribute and/or indicator.

**Comment by smiths** [comment]
Great!  Did the historical program measurement report meet Shahram's needs?  Is there any feedback we should keep in mind for MEASURE 3.0?

**Comment by arana2** [comment]
Yes, the historical program measurement report met Shahram's needs.

None, after meeting with Shahram.  He seemed satisified with the support we provided for him.  

I'm thinking once we obtain the data, we look into making some more reports cross compatible between Windows and MacOS.

**Comment by smiths** [comment]
Yes, increasing the support for different templates on Macs would be great.  We will likely have to speak with Minh to see how much work is involved in doing this.  If we are just generating a report, I feel like the workload won't be too bad.
