### ISSUE TITLE
ELECENG 4OI6 Isn't recognized as a Term 3 course

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#167]
ELECENG 4OI6 shows up with a Warning message for 2017-2018.  According to Shahram (I didn't verify) the warning comes up no matter what term is selected.  Can you please update MEASURE to recognize this as a Term 3 course.  (I remember you sorted this out previously for another Term 3 class.)

**Comment by arana2** [comment]
Hello @smiths 

Shahram is using the incorrect rubric input template.  He is using Rubric Input Template - do not use - for testing only.xlsm and should be using **Rubric Input Template.xlsm**

Would you like me to reach out to Shahram and let him know that he is using the testing template?
![image](https://user-images.githubusercontent.com/38359810/41470134-ba3b104a-707d-11e8-98a3-e513fe83c87a.png)

**Results from using Rubric Input Template.xlsm**
![image](https://user-images.githubusercontent.com/38359810/41470221-009a4196-707e-11e8-86ce-9b67c65bfc46.png)
![image](https://user-images.githubusercontent.com/38359810/41470227-031e2eb4-707e-11e8-9d1d-d1229f3b59bc.png)

**Results from using Rubric Input Template - do not use - for testing only.xlsm**
![image](https://user-images.githubusercontent.com/38359810/41470297-31ce99b0-707e-11e8-818f-8b81db309a3a.png)
![image](https://user-images.githubusercontent.com/38359810/41470303-374d9058-707e-11e8-9e9e-f606b893ecdd.png)

**Comment by smiths** [comment]
I hadn't realized he was using the wrong template.  If possible, it would be good if you either removed that template, made it unavailable to contributors, or at least renamed it to Do Not Use - Rubric Input Template.

If the do not use template is mostly empty, I don't think you need to do anything.  If it is populated with real data, you should let Shahram know that the data will be lost.

**Comment by arana2** [comment]
Thanks @smiths 

I renamed the template to **Do Not Use - Rubric Input Template**. The Vena Admin's are currently using that template to test the Mac defect (#162 ) we raised.  Once the defect is resolved, I will hide it from our users.

Also, I'll reach out to Shahram and notify him of which template to use and what will happen if he entered data in the testing template.

Thank you,
Andrew

**Comment by smiths** [comment]
Sounds great.  Since the problem was related to the incorrect template, I think we can close this issue.
