### ISSUE TITLE
Windows - When closing a template, Vena does not prompt me to check the file back in

### ISSUE THREAD

**Issue by arana2** [smiths/MEASURE#168]
Steps to re-produce: 
1. Contributor View -> Rubric Input & Course Report (by Instructor) -New -> Do Not Use - Rubric Input Template - for testing.xlsm 
2. Check Out 
3. Program: Test 110, Year: 2017-2018 Term 2, Section 1 
4. Save Data 
5. Close (Vena Tab)

Expected Result: When we close the workbook, we expect to be prompted with a pop-up asking if we want to check the file back in. 
Actual Result: No pop-up appears. Have to check in the file through the browser.

Example where it works: 
1. Contributor View -> Faculty Recommendations -> Faculty Recommendations Input Template.xlsm -> Check Out 
2. Year 2017-2018 
3. When we close the workbook (Vena tab -> Close OR the "X" on the top right of the spreadsheet), we are prompted with a Vena - Confirm Checkin pop-up
![image](https://user-images.githubusercontent.com/38359810/41488363-0fd447a6-70ba-11e8-93e3-898753b430cc.png)

We expected the same behaviour for the Rubric Input Template and Course Report (located in the Rubric Input & Course Report (by Instructor) -New)

Vena Ticket:  https://venasupport.zendesk.com/hc/en-us/requests/22683

**Comment by arana2** [comment]
- Fix has been deployed for the Windows environment
- Executed four test cases and all passed
- Test results:  [Vena Test 22683 - Windows_v1.00.docx](https://github.com/smiths/MEASURE/files/2329642/Vena.Test.22683.-.Windows_v1.00.docx)

**Comment by smiths** [comment]
@arana2 what needs to be done to close this issue?  It looks like you were satisfied with your test results.

**Comment by arana2** [comment]
Hi @smiths ,
This issue has been resolved for Windows and currently waiting on an ETA to deploy a fix for MacOS users #169 .  
I was keeping the ticket open in case you had additional feedback.  

If there are no additional comments, I'll go ahead and close this ticket :)

**Comment by smiths** [comment]
Looks good to me.
