### ISSUE TITLE
Tonya - CEAB/VENA Questions

### ISSUE THREAD

**Issue by arana2** [smiths/MEASURE#171]
Tonya sent Andrew a list of Questions:

- Is the previous year’s data available to review? We noticed that there were some courses that had the 2016-17 data and others (that we know was inputted) but not there
- Number formatting – is there an option to change how we input the data, or does it need to be whole numbers (as opposed to decimals or percentages)
- How would we count for MSAF and/or deferred students in our data? 
  - Since the forms are required at the end of each term (and before deferred exams), how do we account for these student while maintaining reliable data?
  - Same for MSAF students (students who ‘waived’ certain assignments/tests due to illness) 
- With regards to courses across all programs (ie. ENG 2P04 is taken by multiple (but not all) departments. Or certain courses that Management & Society students take as well) Who inputs this data? Does it appear in the associated departments? 
  - For example; CIVENG 2A03 is taken by CivEng Students as well as Management & Society. Do we only need to input the data once and it will show up under the Mgmt & Society programs as well?
- Is there a way we can track who has completed their VENA data input rather than having to open up each Course Rubric and check individually?
- I noticed that neither myself nor Prof. Churchill have access to Reports. I know in the meeting a few weeks ago it was mentioned that only certain people should/would have access to this information. Do you have any further details regarding this?

**Comment by arana2** [comment]
Responded to Tonya's inquiries.  Will follow up if Tonya is satisifed with response.

	Is the previous year’s data available to review? We noticed that there were some courses that had the 2016-17 data and others (that we know was inputted) but not there
**AA**:  We can investigate this.  Would you be able to provide the courses that we expect to contain 2016-2017 data?
  
	Number formatting – is there an option to change how we input the data, or does it need to be whole numbers (as opposed to decimals or percentages)
AA:  Which template/file are you looking to change the numbered formatting?

	How would we count for MSAF and/or deferred students in our data? 
o	Since the forms are required at the end of each term (and before deferred exams), how do we account for these student while maintaining reliable data?
o	Same for MSAF students (students who ‘waived’ certain assignments/tests due to illness) 
**AA**:  These are excellent questions and more detailed than what the CEAB requires. 
**AA**:  An instructor doesn’t have to measure every student for every indicator.  We are only required to sample from the class.  In the end it is the percentages of students in each category that matters.  Maybe someday we will go to the point of tracking every student through the program at this level of detail, but this is not currently required.  I would just leave the MSAF, deferred etc, out of the sample.

	With regards to courses across all programs (ie. ENG 2P04 is taken by multiple (but not all) departments. Or certain courses that Management & Society students take as well) Who inputs this data? Does it appear in the associated departments? 
**AA**:  The instructor for the course enters the data.  If a department needs measures from a course that they don’t control, they may have to convey this information to the instructor.  Once a course is measured, it appears in every program where it is used.

o	For example; CIVENG 2A03 is taken by CivEng Students as well as Management & Society. Do we only need to input the data once and it will show up under the Mgmt & Society programs as well?
**AA**: If a course is offered across multiple programs, the data will only need to be inputted once as long as all three conditions are met:
1.	It is for the same course (i.e. CIV ENG 2A03)
2.	It is for the same year and term
•	If course is offered in different terms, the data will need to be entered for each term
3.	It is for the same section
•	If the course is offered in different sections, the data will need to be entered for each section
**AA**:  Also, in cases where there are multiple sections, all of the data is aggregated into the first section.  It is only when someone has an interest in tracking the differences between sections that we would make an effort to treat these as separate sections.

	Is there a way we can track who has completed their VENA data input rather than having to open up each Course Rubric and check individually?
**AA**: Today, there is a way to track who has started entering data.  This can be achieved generating the Rubric Entry Report
Steps:
1.	Go into Contributor View
2.	Select Reports
3.	Select Rubric Entry Report
•	If a popup appears to enable editing, Click “enable editing” button
4.	Once open, select the program, year/term, section

	I noticed that neither myself nor Prof. Churchill have access to Reports. I know in the meeting a few weeks ago it was mentioned that only certain people should/would have access to this information. Do you have any further details regarding this?
**AA**:  Yes, access to the reports are given to the Department Representative for Vena and to those requesting it (i.e. Professors and data entry users)
-	Professor Churchill should be able to access the reports as well as yourself

**Comment by arana2** [comment]
- Unable to retrieve course data for CIV ENG 2E03 (2016-2017; Term 1) and CIV ENG 3C03 (2016-2017; Term 1)
- Will reach out to VENA
- Asked Tonya if she has the rubric input template document for those two courses (as reference)

**Comment by arana2** [comment]
8/8/2018
- Responded to Tonya 
- Confirmed CIV ENG 2E03 had incomplete data and CIV ENG 3C03 did not have any data

- With Vena's support, I was able to retrieve and review the Vena database along with the backups created each year going as far back as the 2014-2015 term via **Audit Trail**
- As a sanity check, I reviewed the documents shared by Tonya (CEAB Course Measurement Record CE 3C03 2016-17.docx and CIVENG 2E03 CEAB Course Measurement Record 2E03 Fall 2016.docx) and cross-referenced them against every CIV ENG course that had data entered
- I can confirm the CIV ENG 2E03 and CIV ENG 3C03 was not keyed erroneously into another course

Next steps:
- Suggested Tonya to enter the 2016-2017 CIV ENG 2E03 and CIV ENG 3C03 rubric data into the Rubric Input Template

@smiths - May we close this ticket?  I don't think we need to keep this open unless Tonya follows up with additional information

**Comment by smiths** [comment]
Yes, we can close this ticket.
