### ISSUE TITLE
Virtual Desktop - Expired Security Certificate

### ISSUE THREAD

**Issue by arana2** [smiths/MEASURE#173]
Users are unable to access their virtual desktop to enter data for Vena.

Spencer reached out to Derek to assist Andrew.

![capture](https://user-images.githubusercontent.com/38359810/42693538-73e147e8-867d-11e8-8413-8d697b785ba2.jpg)

**Comment by smiths** [comment]
@arana2, if you haven't heard back from Derek, please send him a reminder e-mail.

**Comment by arana2** [comment]
Derek has updated the security certificate.  Users should be able to access the VM again.
