### ISSUE TITLE
Contributor Guide Department: Update Mapping Between Courses and Programs

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#18]
I cannot find in the documentation any instructions on how to edit the mapping between courses and programs at the start of each academic year.  Although our curriculum is relatively stable from year to year, there will always be some changes.  As we discussed, each department will edit the list of courses that belong to each program.  I believe the changes are doing by dragging and dropping through Modeler^2.0/Data Modeller/Members/Program in Vena.

We should add a section to the Contributor Guide -- Department, to describe how to do this.

**Comment by EvanVena** [comment]
Added section "Edit Courses and Programs Mapping"
in both ADMIN guide and Contributor Guide -- Department.

**Comment by smiths** [comment]
The new section looks good to me.  We will have to edit the timeline at the start of the document to correctly point to the correct sections of the documents, but I think we should wait to do this until we are sure that the documents are stable.
