### ISSUE TITLE
Vena Data Recovery Process

### ISSUE THREAD

**Issue by arana2** [smiths/MEASURE#182]
- Confirm Vena is available and can provide a prompt response in case there is a high priority issue (e.g. database cannot be accessed, data is corrupted, data cannot be recovered) 
- Will need documentation on how to recover backup data and confirm response rate in case of an emergency
- Also, understand how quickly can data be recovered (if database breaks, how fast can we get the data?)
- Once we understand the process, add to timeline document and flowchart

**Comment by arana2** [comment]
- Per #181, Vena has confirmed nightly backups are performed and can be retrieved
- Vena Vena is confirming if we will have the capability to backup and recover the data ourselves – most likely yes, but will need documentation and testing

**Comment by arana2** [comment]
- Per #187, added the Backup and recovery process to the Admin guide and Accreditation Flowchart

- [ ] Vena will provide Andrew with the backup process and documentation
- [ ] Vena will provide Andrew with Read access to the data model for backup purposes
- [ ] Andrew to confirm with stakeholders if they have a preference to where the data resides when the backup and restore process is tested.  As per current mode of operation, test data is stored in the USA as part of the backup and restore process.

**Comment by smiths** [comment]
This is great to see this coming together @arana2.  If people suggest that we switch to an ad hoc web-based solution in the future, we should ask them if their back up procedure is as well thought out as this.  I particularly like the off-site aspect of the backup.

**Comment by arana2** [comment]
Agreed.

@smiths ,
Part of the backup and restore process is to store the test data at another geographical location then recover it.  Vena would occasionally store it in the USA to test their disaster recovery plan.  I'm hoping to obtain confirmation from our stakeholders to see if they are okay with this, or if McMaster prefers to store the test data within Canada.

Michal C. has pointed me to confirm this information with our stakeholders.  Should we be asking Maria and Ken for their feedback?

**Comment by smiths** [comment]
I noticed that item in your summary.  I doubt it matters very much, since we aren't storing any personal data on anyone.  This isn't research related data or personal data.  You should check with Maria.  She can either answer, or redirect you.

**Comment by arana2** [comment]
- Sent email to Maria for confirmation

**Comment by arana2** [comment]
Per Graduate Attribute Discussion on Tues Oct 23, 2018
- Maria (stakeholder) confirmed it will be ok to have this data re-stored in the US since it does not contain any student data (student numbers or student numbers)

**Comment by arana2** [comment]
- Closing this ticket since we received the information needed (1. obtain Maria's confirmation, 2.  Understand the Disaster Recovery Plan, 3.  Exporting Vena Data Model) 
- Opening two tickets for tracking purposes:
- #196 - Executing the Disaster Recovery Plan
- #197 - Exporting Vena Data Model
