### ISSUE TITLE
Stakeholder Meeting with Vena End-Users

### ISSUE THREAD

**Issue by arana2** [smiths/MEASURE#184]
- Coordinate a separate meeting with to obtain ideas, user feedback, and priorities for MEASURE 3.0
- Tentative List:  Maria White., Spencer Smith., Jake Nease, Sinisa, Andrew, and program representatives
- We will need to obtain a list of program representatives

**Comment by arana2** [comment]
Confirmed Session
Date: Thursday November 1, 2018 
Location:  JHE 265
Duration:  3:00PM to 4:00PM

**Comment by arana2** [comment]
Takeaways:

- Shahram requested ability to genereate a CEAB Attribute report for multiple years (good to see current trends)
- Shahram requested more Mac support for some of the reports
- All stakeholders agree a combined template containing ability to enter rubric data, continual improvement, and section containing generated report
- Upload a static rubric input template for users to ender their data
- Sinah considered having drop-in sessions to support users entering data

**Comment by smiths** [comment]
Great summary @arana2.  I only have one minor comment to add.  We should verify that if a specific course appears in more than one measurement map that the indicators that are included in the generated rubric are the union of the indicators "indicated" in each measurement map.  I'm pretty sure this is the case, but at some point we should verify this.

Good meeting.  Plenty of reason for optimism.  😄

**Comment by arana2** [comment]
Thank you for the support and additional information! 

I will add these to the meeting notes that will be sent out today.
