### ISSUE TITLE
Add an Instructor Field to the Rubric/Course Report Template

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#194]
Although it isn't a high priority, it would be nice to know the instructor for a course when reviewing the course reports.  I've been reviewing data for my department recently and I was wondering who actually taught (and measured) the courses I was looking at.

It would be easy (I believe) to simply have a field to enter the instructors name.  If we go the route of explicitly assigning the courses to instructors, then this field could be auto-populated in the generated report.

**Comment by arana2** [comment]
This is a good idea.  I will update the task list to understand the best way to approach this.

**Comment by arana2** [comment]
This field has been implemented for MEASURE 3.0
