### ISSUE TITLE
Static Rubric Input Template

### ISSUE THREAD

**Issue by arana2** [smiths/MEASURE#198]
Based on the questionnaire feedback, faculty members may use their own method when preparing their rubric information for data entry.  In some cases, faculty members designate a representative to submit data to Vena.  The representative may receive multiple rubric information in various formats.  This may result in misinterpretation of the information and additional workload associated with understanding different formats.

![image](https://user-images.githubusercontent.com/38359810/48644942-20e30700-e9b2-11e8-9fe4-cddcdbd076b4.png)

To encourage consistency, McMaster IT will distribute a Static Rubric Input Template on the measure.mcmaster.ca website.  

Instructors will use this template to enter in their rubric data for the representative to submit in Vena.

**Comment by arana2** [comment]
Created and uploaded the Static Rubric Input Template to the measure.mcmaster.ca website.

Reference:  https://www.eng.mcmaster.ca/sites/default/files/static_rubric_input_template_v1.01.xlsx

**Comment by smiths** [comment]
Hello @arana2.  Thank you for posting this.  Your static template highlights the problems with faculty members delegating filling in their rubrics.  To be general  your static template needs to include all attributes and indicators, even though each course only covers some of them.  Moreover, your static template cannot know anything about an individual courses learning outcomes.  In the general form that static template needs to be in, I'm not sure how helpful it is.  There would be extra work typing in the line items for each course, even when that work has already been done.

Maybe for those departments that have TAs entering the data, the TAs can send the actual rubric, with the customized indicators and learning outcomes to the instructors?  It would mean customized e-mails to each instructor, but it would save the TA on the data entry later.  Of course, the simpler solution is for faculty members to enter the data themselves.  😄 

We will have to update this static rubric template if we end up combining the rubric and the course report templates.

**Comment by arana2** [comment]
Hi @smiths ,

Thank you for the feedback.   I agree.  The static input template will not resolve the issue for faculty members delegating representatives to input the rubric data.  The static template will still need to be customized to reflect the learning outcomes and expectations for each course.

Until we get everyone on board with Vena, I like the idea of having TAs or a delegate customizing the rubric input template and having the instructor to input the expectations and numbers.

Correct, this static rubric template will be updated when we align on a solution with regards to combining the rubric and course report template.  More to come on this.

**Comment by arana2** [comment]
- Static Rubric Input Template v1.02 has been uploaded to measure.mcmaster.ca
  -  https://www.eng.mcmaster.ca/sites/default/files/static_rubric_input_template_v1.02.xlsx
- Template no longer includes Graduate Attribute 13 - Sustainability but includes a field to enter the Instructor's Name and Rubric Entry Status
- The static template does not include the summary and detailed course report because the VBA macros require Vena's "Refresh Data" feature to regenerate the charts with updated data
-  To access the Rubric Input Template's Summary and Detailed Course, users will need to access the template in Vena 
- As a reminder, this template is intended for instructors who designate a representative to submit data in Vena.  In a steady-state, instructors will be entering the rubric data directly to Vena and eliminate the need for the static rubric input template
