### ISSUE TITLE
Solution Design Document - MEASURE 3.0

### ISSUE THREAD

**Issue by arana2** [smiths/MEASURE#199]
The solution design is a high-level document describing how the solution will be implemented to address every task item.

For each task item, the solution design may include:
-	High-level design approach
-	Alternative solutions
-	Flowcharts
-	Data flow diagram describing the technical solution
-	Best practises guidelines describing project phases and tasks
-	Feasibility and effort estimate for each task item based on Vena’s experiences

**Comment by smiths** [comment]
Sounds great!

**Comment by arana2** [comment]
- The solution design was added to the MEASURE 3.0 Task List document and the latest version is 3.01
- Internal review of the solution design was completed on Tues Dec 18 - Team has aligned to the solution and added suggestions
- Shared MEASURE 3.0 Task List Dv3.01 with Vena Team on Dec 19, 2018
