### ISSUE TITLE
Contributor Guide - Instructor

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#20]
The contributor guide for the instructors should have less information in it.  We don't want to scare the instructors off.  :-)  There main concern will be doing what they have to do.  For this reason, I suggest moving the discussion of all of the reports, except the course report, to the contributor's guide for the department.  Specifically, I think the discussion of the following reports should be moved to the departments guide:

1) Attribute Map Report

2) Attribute Map Summary Report

3) Indicator Map Report

4) Historical Course Measurement Report

5) Historical Program Measurement Report

The course report should also be included in Section 2 on inputs, since the instructors are expected to fill in their section of the course report.

**Comment by EvanVena** [comment]
Moved.

**Comment by smiths** [comment]
Looks good.
