### ISSUE TITLE
T-02 Enhanced Rubric Report Testing

### ISSUE THREAD

**Issue by arana2** [smiths/MEASURE#206]
Expected Results
-	Rubric Entry Report to display:
o	Default sort by Status (Not Started, Started, Complete)
o	Display last user to save the rubric data with the save date (if applicable)
	These fields will be cleared after new academic year is created
o	Display instructor name beside each course (if applicable)
o	Summary Section
	Display number of courses Not Started, Started, Complete, and Total for each program

-	Expected Rubric Entry Report (from Rubric Entry Report Wireframe – MEASURE 3.0 Task List v3.01.docx):

**Test 1**
Description: 
-	Generate Rubric Entry Report for Entire Year (17-18)
o	Program: Test Engineering (Test Eng)
o	Term: 2017-2018
o	Section: 1

-	Entered Rubric data for: 
o	TEST 101 Term 1 (17-18)
o	TEST 102 Term 2 (17-18)

Actual Results
![image](https://user-images.githubusercontent.com/38359810/52288328-fca42000-2939-11e9-829e-2c73082dbcf5.png)

- [x] Rubric status not retrieved for TEST 101 and 102 when selecting the report for the 2017-2018 Year
- [x] Status cells are all set to 0 – this field for each course should display the status of the course
- [x] Measured cells are all set to 45 – what is this field used for?
- [x] Measure Required field only has one course populated with NO
- Every course in the Test Engineering program should be set to YES because the Measured Indicators template has been updated to require at least 1 measured indicator to be populated

- [x] Instructor cells are set to 0 for all courses
- Test 101 should display – Andrew Aran
- Test 102 should display - John Smith

- [x] Last Rubric Saved By cells are all set to 0
- Test 101 should display – Minh Le
- Test 102 should display – Andrew Aran

- [x] Last Rubric Save Time  are all set to January 0, 1900

**Test 2**
Description:
-	Generate Rubric Entry Report for Term 1 (17-18)
o	Program: Test Engineering (Test Eng)
o	Term: 2017-2018 Term 1
o	Section: 1

-	Entered Rubric data for: 
o	TEST 101 Term 1 (17-18)

Actual Results
![image](https://user-images.githubusercontent.com/38359810/52288398-20fffc80-293a-11e9-8f92-710ef4a11b19.png)
![image](https://user-images.githubusercontent.com/38359810/52288410-23625680-293a-11e9-9649-a777264b9325.png)

- [x] Status cell – correctly displaying WIP
- [x] Measured cells are all set to 45 – what is this field used for?
- [x] Measure Required field only has one course populated with NO
- Every course in the Test Engineering program should be set to YES because the Measured Indicators template has been updated to require at least 1 measured indicator to be populated

- [x] Instructor name – correctly displaying Andrew Aran
- [x] Last Rubric Save Time – not showing anything – should show my last save date (Feb 5, 2019)
- [x] Default sort by Status (Not Started, Started, Complete) was not implemented

**Test 3**
![image](https://user-images.githubusercontent.com/38359810/52288534-66bcc500-293a-11e9-8d72-7475e8052742.png)
![image](https://user-images.githubusercontent.com/38359810/52288496-54db2200-293a-11e9-88f6-b382bf39902c.png)

- [x] Status cell – correctly displaying Fully Complete
- [x] Measured cells are all set to 45 – what is this field used for?
- [x] Measure Required field only has one course populated with NO
- Every course in the Test Engineering program should be set to YES because the Measured Indicators template has been updated to require at least 1 measured indicator to be populated
- [x] Instructor name – correctly displaying John Smith
- [x] Last Rubric Save Time – not showing anything – should show my last save date (Feb 5, 2019)

- [x] Default sort by Status (Not Started, Started, Complete) was not implemented

**Comment by arana2** [comment]
This issue has been resolved and is working as expected for both Windows and macOS

See screenshots below:
**Windows 10 - Excel 2016:**
![image](https://user-images.githubusercontent.com/38359810/58658644-ebb75a00-82ee-11e9-88ee-400fd7c6b3f3.png)

**macOS Mojave - Excel for Mac (Office 365)**
![image](https://user-images.githubusercontent.com/38359810/58660858-6afb5c80-82f4-11e9-86b1-df2aa2ce3b4a.png)

**Comment by smiths** [comment]
Great!
