### ISSUE TITLE
S-01 Fix the Order of the Learning Outcomes (line items) Testing

### ISSUE THREAD

**Issue by arana2** [smiths/MEASURE#207]
**Information**
Course Name: TEST 104
Year: 2019-2020, Term 2
Section: 1
Tester: Andrew Aran
Date: February 19, 2019
Tenant: mcmasterdev2
Filename: Rubric Input Template V2 WIP.xlsm

**Test Rubric Input Template for New Year**
-	LID’s from 2018-2019 are not displaying in 2019-2020 
o	LID’s from 2018-2019 should be rolled over to 2019-2020
o	Vena, please review production environment to confirm the LID's and associated values required to roll over

![image](https://user-images.githubusercontent.com/38359810/53046414-f6e02b80-345d-11e9-9333-b4a615f9d6d4.png)
- Instructor name will not roll over
- Values from Summary of Actions to be Taken for Continuous Improvement for Next Academic Year will not roll over
- New rubric entry status will not roll over

**Comment by arana2** [comment]
The new template contains Vena Macros which is currently not supported by MacOS.

Need to consider alternative solutions for MacOS users.

**Alternative 1 - All users using WIndows-based template**
- Require all users to only use the Windows-based template
- MacOS users will need to connect to a VM to access the Windows-based template
- This will ensure all users are using the same template but may lose support from the MacOS users

**Alternative 2 - Separate templates for Windows and MacOS users**
- Windows users will use the new template containing Rubric Input and Course Report for rubric entry
- MacOS users will use the current Rubric Input template and Course report for rubric entry
- macOS users will not have to access a VM to enter their rubric data.  However, will the updated Rubric Entry Status Report be able to record the status, instructor name, last rubric saved by name, and last rubric save time information?  This may be based on the Vena macro created by Minh.

**Comment by arana2** [comment]
**Re-Test**

- TEST 101
- Term 2018-2019 Term 1, Term 2019-2020 Term 1
- Section 1

I was able to successfully created a new academic year.  However, the new academic year has some issues:

-	Issue 1:  The Attribute and Indicator row dividers have been removed
-	Issue 2:  The order of the LID’s are still not in order

**Test Tenant (2018-2019)**
![image](https://user-images.githubusercontent.com/38359810/54532061-3e72ae00-495d-11e9-841a-a07a21ae5af9.png)

**Test Tenant (2019-2020)**
![image](https://user-images.githubusercontent.com/38359810/54532097-50ece780-495d-11e9-9beb-5433ec0fbf46.png)

**Comment by arana2** [comment]
**Test 3 Results**
- Pass
- The order of the learning outcomes is maintained when a new year is created.  Prior year also remained unchanged.
 
1.  Enter rubric data
In Windows environment entered rubric data for:
- Tenant: mcmasterdev2
- Course: TEST 101
- Term: 1 2018-2019
- Section: 1
- Indicators: 1.2, 3.2, 13.4, 13.5 (4 learning objectives per indicator)

In macOS environment entered rubric data for:
- Tenant: mcmasterdev2
- Course: TEST 102
- Term: 2 2019-2020
- Section: 1
- Indicators: 1.1, 5.2, 12.2 (4 learning objectives per indicator)

2. Create 2019-2020 Year
![image](https://user-images.githubusercontent.com/38359810/56669706-92209780-667f-11e9-95b1-09a684ccf78b.png)

3. Update Global Variable
- Update current term to 2019-2020 Term 2
![image](https://user-images.githubusercontent.com/38359810/56670397-c5175b00-6680-11e9-8683-7b6e29c8b539.png)

4. Confirm order of learning outcomes are maintained in the new year

- [ ] Windows Test 101
![image](https://user-images.githubusercontent.com/38359810/56671038-e2005e00-6681-11e9-925f-2bc8a4ea99ff.png)

- The order of the learning outcomes was successfully maintained when moved to the new 2019-2020 year
- The 2018-2019 order of the learning outcomes was unchanged

5. Enter rubric data for macOS 2019-2020
- [ ] macOS Test 102

5.  Create 2020-2021 Year
![image](https://user-images.githubusercontent.com/38359810/56674953-001d8c80-6689-11e9-95d8-ab3560bc8b1e.png)

6.  Confirm order of learning outcomes are maintained in the new year
- [] Windows Test 101
![image](https://user-images.githubusercontent.com/38359810/56674415-02cbb200-6688-11e9-84da-e6dd5d5ad780.png)
- The order of the learning outcomes was successfully maintained when moved to the new 2020-2021 year
- The 2019-2020 order of the learning outcomes was also unchanged
- [ ] macOS Test 102
- The order of the learning outcomes was successfully maintained when moved to the new 2020-2021 year
![image](https://user-images.githubusercontent.com/38359810/56674776-9c935f00-6688-11e9-9a7e-4424319cff7a.png)

- The 2019-2020 order of the learning outcomes was also unchanged
![image](https://user-images.githubusercontent.com/38359810/56674792-a7e68a80-6688-11e9-8708-0d85f1752137.png)

**Comment by arana2** [comment]
- Changes were implemented in Vena's SQL server
- No changes are required for our templates/reports

**Comment by smiths** [comment]
Great to see this issue closed!
