### ISSUE TITLE
Unmap Grad Attribute - Sustainability (13)

### ISSUE THREAD

**Issue by arana2** [smiths/MEASURE#215]
- Requested during the GA meeting, unmap Graduate Attribute - Sustainability (13) from all Vena templates and reports
- Do not delete the attribute, just hide it from being visible

**Templates**

- [x] Curriculum Committee Recommendations Input Template.xlsm

- [x] Curriculum Mapping Input Template.xlsm

- [x] Measured Indicators Input Template.xlsm

- [x] Rubric Input Template.xlsm

**Reports**

- [x] Attribute Map Report.xlsm

- [x] Attribute Map Summary Report.xlsm

- [x] CEAB Attribute Report.xlsm

- [x] Course Report.xlsm

- [x] End of Term Backup Data Model.xlsm

- [x] Faculty and Curriculum Committee Recommendations Report.xlsm

- [x] Historical Course Measurement Report.xlsm

- [x] Historical Program Measurement Report.xlsm

- [x] Indicator Map Report.xlsm

- [x] Measurement Map Report.xlsm

- [x] Rubric Entry Report.xlsm

**Comment by arana2** [comment]
- Graduate Attribute Sustainability has been successfully unmapped from all templates, reports, and Vena Model
- Before unmapping, backed up all the templates and reports (in case the sustainability attribute needs to be added back)
- Course Report contained VBA code to generate charts (had to modify the code to bypass retrieveing and generating charts for Sustainability)

Reminder for @arana2: When MEASURE 3.0 is complete, the VBA code will need to be updated to bypass Sustainability

**Comment by smiths** [comment]
Sounds good @arana2!
