### ISSUE TITLE
Update Rubric Input Template

### ISSUE THREAD

**Issue by arana2** [smiths/MEASURE#228]
- [x] Update the "Last User" label.  The current label is unclear

- [x] Add a better description for the "RefreshCharts" button,  Consider including a tooltip

- [x] For visibility, add colour to the worksheet tabs for Summary and Detail View charts

**Comment by arana2** [comment]
- Changed "Last User" label to "Updated By:' in the macOS Rubric input template and Rubric Entry Report
![image](https://user-images.githubusercontent.com/38359810/60130830-0baf3180-9766-11e9-8645-bf78cca892b1.png)
- Added a tooltip next to the Refresh Charts Button
![image](https://user-images.githubusercontent.com/38359810/60130872-1b2e7a80-9766-11e9-8ecb-bf1551062104.png)
- For visibility, changed the worksheet tab colour of the Summary and Detailed View 
![image](https://user-images.githubusercontent.com/38359810/60130952-4022ed80-9766-11e9-92a4-1b988046eec6.png)

**Comment by smiths** [comment]
Great!
