### ISSUE TITLE
Add a Timeline at the start of Each User Document

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#23]
The user manuals (Admin Guide, Department Guide and Instructor Guides) will be critical to the success of MEASURE 2.0.  The first thing people will look for is what they are expected to do.  I think we can capture this best with a timeline at the start of each document.  Can something similar to the attached file be added to each document?  We can edit the table going forward, but I think having it in the documents will help us make sure that the documents (and the timeline) are complete.  To start with all of the documents can have the same timeline, although we will likely later simplify the instructor timeline to only mention the tasks that are relevant to them.

[AnnualTimeline.docx](https://github.com/smiths/MEASURE/files/442749/AnnualTimeline.docx)

**Comment by EvanVena** [comment]
added 1.4 for the timeline

**Comment by smiths** [comment]
Looks good.  We'll still want to edit the timelines, but this is a great start.
