### ISSUE TITLE
Test Add New Course and Edit Course and Program Mapping

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#24]
Hello Michelle.  Can you please update either the 2013-2014 or 2015-2016 curriculum in Vena for either Mech Eng or Chemical Eng.  The specific choice doesn't matter.  Please pick the one that is easiest.  You also do not have to do all of the changes if they are substantial.  The goal is to test the instructions for adding new courses and for editing the course and program map (Sections 7 and 8) of the Admin Guide.

Please let me know if you have any questions.

**Comment by zhengm2** [comment]
@smiths I tried to add a course and got the following error: You can't make structural changes to a started process. Please pause the process to make structural changes. Perhaps when @JoeSpan is done testing I can pause the process and try it.

**Comment by zhengm2** [comment]
@bhancas @EvanVena When making curriculum changes. How do I know which year I am working on? Can I only make changes to the year we are entering data for?

**Comment by EvanVena** [comment]
Only the current year program hierarchy is at the model (most up to date
one)
this is the assumption we made during the initial design.

Thanks
Evan

**Comment by smiths** [comment]
Yes, we only want to be able to edit the current year.  Michelle, this might seem a bit odd now, but once we get to steady-state, there won't be any reason to edit any years other than the current one.  Given that Joe and Maria want to focus on 2016-2017 going forward, we don't really have to worry too much about the previous years.

@EvanVena, how do we know what the current year is?  It won't matter going forward, but for right now, I'm not sure.  @zhengm2, you can either edit the current year (once we know what that is), or you can created 2016-2017 and start editing that.

**Comment by smiths** [comment]
@zhengm2 with respect to pausing the process, we don't need to wait for the testing to be done.  We just need to make sure that we do it at a time when neither Joe or Sam are entering any data.  If you know when you are going to try to add a new course, you can send us all an e-mail and warn us to not access the system at that time.

**Comment by smiths** [comment]
After looking around, I see that we can determine the current year by the global variable in the Manager/Files Library/Data Controls in the file Input Variables Template.  The current value is 2015-2016 Term 2.

**Comment by smiths** [comment]
How far did  you get with this testing Michelle?  I'm assuming that you were able to do at least one test case with each item described in the Admin Guide.  If that is the case, you can close this issue.  Our next step will be training the departmental reps to update their programs, curriculum maps and measurement maps.

**Comment by zhengm2** [comment]
@EvanVena I followed the instructions in the ADMIN guide on how to add new courses and I am not able to do this successfully. Can you please confirm if the instructions are accurate and/or if there is another way to do it?

**Comment by EvanVena** [comment]
Can you share with me the instruction you followed?

Thanks
Evan

**Comment by smiths** [comment]
Hello Evan.  Michelle is currently away for a week, so I will answer your question.  She followed the instructions given in the documentation that you wrote.  We have started re-organizing the documents for their intended audiences, but you can find your original instructions in Section 6 (page 16) of the DeptGuide.docx document.  As always, you can find the latest version of the documentation on GitHub.

**Comment by EvanVena** [comment]
Hi Spencer,

I took a look at the DeptGuide on Github and it seems a bit outdated and
confusing on adding new course and assigning a course to a process.
I updated the both sections, and followed the instruction on creating a
test course, and it worked.

Please see the updated version of this document.

Thanks
Evan

**Comment by smiths** [comment]
Hello  Evan.  Where is the updated version?  I cannot see it.  Maybe you should try pushing right to the repo?  The instructions are given with issue #86 .

**Comment by EvanVena** [comment]
I uploaded it again to the Github, please check.
Evan

**Comment by zhengm2** [comment]
Hi @EvanVena and @smiths, I am able to add a course (Eng Phys 4U02) but how can this course be mapped to the Eng Phys curriculum?

**Comment by zhengm2** [comment]
Sorry @EvanVena, I followed the wrong instructions. I was able to add a course with no issues using the new instructions. Please see below. Is there a reason why the new course is not bolded and the existing course is?
![new course](https://cloud.githubusercontent.com/assets/20647879/19984378/72e2ec86-a1e4-11e6-9d1d-c023fbdb2912.JPG)

**Comment by smiths** [comment]
Hello @zhengm2 .  I believe I can answer your question.  In the list of courses a bold course means that it appears in the more than one program.  If a course is only in one program, it is not bold.  Since the new course is only in Eng Phys Level IV, it isn't bold.  I think if you add it to other programs, like Eng Phys and Society, it will become bold.

**Comment by EvanVena** [comment]
@zhengm2 @smiths 
Yes Spencer, if you shared you dimension with other parent level, it will appear to bold.

Thanks

**Comment by EvanVena** [comment]
You are use the share function in Vena
you can find the description under the Department Guide 6.2
Thanks
Evan
