### ISSUE TITLE
Why are there Terms 4 and 5 options available?

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#26]
When selecting a year for a course in the rubric template there are options for Terms 1, 2, 3, 4 and 5.  Terms 1, 2 and 3 make sense (Term 3 at McMaster means a course that runs for both terms), but 4 and 5 do not.  Also there is a Default option.  What does this mean?

**Comment by smiths** [comment]
Evan to look into what Default means in this case.

**Comment by EvanVena** [comment]
We used the default to hold the value that can not put into the term.
for example: when we archived the data for 2014-2015, all terms data will be aggregated into 2014-2015 Default.

Hope this help.

Evan

**Comment by smiths** [comment]
Hello Evan.  I'm sorry, but your explanation does not help.  If I am going to change the data for a rubric, when would I select 2014-2015 Default?  What will happen if an instructor selects Default, but they should have selected Term 1 or Term 2?  I am worried that we will have data entered into the system and not be able to find it in the future.

**Comment by EvanVena** [comment]
@smiths @bhancas  Hi, Instructor should always select the correct term.
the Default Term is for holding information(data) at the back end.

**Comment by smiths** [comment]
Thank you for the information Evan.  If the instructor should never select Default Term, is there a way to make it not visible?  I find the best way to avoid errors is to restrict input choices so that the error is not possible.

**Comment by EvanVena** [comment]
Hi @smiths @bhancas 
I created a process to hide the Default year selection in the rubric input template.
please see the picture below
![image](https://cloud.githubusercontent.com/assets/20912011/18329068/d4b19a9e-751f-11e6-9305-5fae9f1b2c80.png)

**Comment by smiths** [comment]
Looks great!  Thank you Evan.
