### ISSUE TITLE
Update Course Mapping to Program (2020-2021)

### ISSUE THREAD

**Issue by arana2** [smiths/MEASURE#268]
- Review Academic Calendar for programs
- Update the programs based on the academic calendar

- [x] **Update Vena Program Structure:**
- Program
  - Example: Civil Engineering (B.Eng)
- Program with IBEHS
  - Example: Civil and Biomedical Engineering (B.Eng.BME)
- Do not include electives

**List of programs to update:**
- [x] Chemical and Biomedical Engineering Co-Op (B.Eng.BME)
- [x] Civil and Biomedical Engineering Co-Op (B.Eng.BME)
- [x] Electrical and Biomedical Engineering Co-Op (B.Eng.BME)
- [x] Engineering Physics and Biomedical Engineering Co-Op (B.Eng.BME)
- [x] Materials and Biomedical Engineering Co-Op (B.Eng.BME)
- [x] Mechanical and Biomedical Engineering Co-Op (B.Eng.BME)
- [x] Mechatronics and Biomedical Engineering Co-Op (B.Eng.BME)
- [x] Software and Biomedical Engineering Co-Op (B.Eng.BME)

**Review courses associated to these programs if there are any changes**
- [x] Engineering I
- [x] IBEHS
- [x] Chemical Engineering (B.Eng.)
- [x] Civil Engineering (B.Eng.)
- [x] Computer Engineering (B.Eng.)
- [x] Electrical Engineering (B.Eng.)
- [x] Engineering Physics (B.Eng.)
- [x] Materials Engineering (B.Eng.)
- [x] Mechanical Engineering (B.Eng.)
- [x] Mechatronics Engineering (B.Eng.)
- [x] Software Engineering (B.Eng.)

**Once complete, notify Department Representative for review**

**Comment by arana2** [comment]
- 50 programs in Vena have been updated to reflect the 2020-2021 academic calendar
- Calendar reference:  https://academiccalendars.romcmaster.ca/content.php?catoid=41&navoid=8648

**Comment by smiths** [comment]
@arana2, when we meet with the capstone computer science team, we should discuss finding a means to automate updating the curriculum.  :smile:  Thank you for your efforts to update the curriculum.  That is a big job!
