### ISSUE TITLE
Should we add a warning to the Instructor Guide to select the right year?

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#27]
I believe that when an instructor selects their course for their rubric input they are free to select any year.  Should we add a warning to the documentation to make sure that they select the correct year.  Will the software suggest the current year by default?

**Comment by smiths** [comment]
Let's mention the importance of the year and term in the manual.

**Comment by EvanVena** [comment]
HI @smiths @bhancas 
I added a soft validation to all the input template, before the save the data.
please see the attached pictures.

Also i altered the Default Year variable to the term level, so all default year and term warning cab be driving by this one global variable.

I will also update the ADMIN guide to reflect  this changes.

![image](https://cloud.githubusercontent.com/assets/20912011/18251190/ac0e4004-7355-11e6-827c-0068bd436790.png)

 
![warning year](https://cloud.githubusercontent.com/assets/20912011/18251116/3817d66a-7355-11e6-930e-179f8c7fda3a.PNG)
![warning term](https://cloud.githubusercontent.com/assets/20912011/18251115/38169084-7355-11e6-85c8-ef7bdad788cc.PNG)

**Comment by smiths** [comment]
Looks good.  Yes, please add the steps for setting the default term to the Admin Guide.  We will have to change the term at the start of a new academic year (September) and at the start of a new term (January).
