### ISSUE TITLE
Default Term

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#29]
Let us add a default term to issue a warning when the user has selected another term.

**Comment by smiths** [comment]
Evan, can you please hold off on doing this for a bit.  I would like to discuss the option of removing terms all together.  I'll send you and Bogdan and e-mail about this.

**Comment by smiths** [comment]
After an investigation, I see that we offer more courses in both terms that I thought.  Can you please renew the plan of issuing a warning when a user tries to enter data for a term other than the default term.

**Comment by EvanVena** [comment]
please see the reply on #27

**Comment by smiths** [comment]
This issue was addressed by revisions to the admin guide, as explained in #27.
