### ISSUE TITLE
Instructors Cannot See "Curriculum Committee Recommendations Report"

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#30]
We would like the instructors to review the previous year's "Curriculum Committee Recommendations Report," but I don't think it is currently available to them.  How do we make this visible.  I assume that this isn't difficult to do, but I don't know how you communicate in Vena that the instructors can see this report.  This came up when @SamGrimshaw was following through the latest version of the Instructor Guide.

**Comment by EvanVena** [comment]
@smiths @bhancas 
Added to the report library

![image](https://cloud.githubusercontent.com/assets/20912011/18251314/8199adee-7356-11e6-8ea8-1574cd9d4d7a.png)

**Comment by smiths** [comment]
Hello Evan.  I think you might have misunderstood my question.  I know where I can access the template; I want to know how the instructors are supposed to access it.  Since it is an input form for them (as well as output), I though it might appear as part of the work flow activities for "Chem Eng Rubric."  Alternatively, maybe we just add instructors as Users for the template.

I think this is more of a best practices questions for Vena users.  We haven't set up the system with user permissions yet and I'm not sure exactly how this is done.

**Comment by smiths** [comment]
The security information was changed so that instructors can see the reports.  A separate issue #61 discusses what needs to happen for someone to reach this task.  The current issue can be closed.
