### ISSUE TITLE
Rubric Data Entry General Feedback

### ISSUE THREAD

**Issue by SamGrimshaw** [smiths/MEASURE#34]
The 2015/16 data has been entered into the 'Complete Rubric' along with the 2013/14 data for the core chem eng courses. The file has been submitted.

Here's some general feedback I've noted while going through the data entry process: 

1) Measured indicators did not align with the default indicators on display in the 'Complete Rubric' template. This wasn't an issue for courses that repeated the same indicators from the previous year, but many courses removed/added measured indicators to their respective course reports. I don't understand why the submitted 'CHEM ENG Measured Indicators' for a particular course/term combo did not affect the indicators on display for the same course/term in the 'CHEM ENG Complete Rubric'. I cannot add indicators listed in the complete rubric, which is sort of annoying. I would almost prefer having all the indicators shown, but selecting 0 or 1 at will in the 'use' column according to what was actually measured in the original course report. I'm already selecting 0 in that column when a particular indicator was no longer measured in one course offering. 

2) Probably not an issue if professors are individually entering data, but sometimes I would experience a glitch where the data tables simply would not load. Re-checking in was required to fix.

3) Also, adding files via the 'comments' tab sometimes worked, but was inconsistent. Other times, clicking the 'comments' tab would do nothing and no menu appeared giving you the option to upload a file. Re-checking in would not necessarily fix the later issue, depending on the course. For example, I couldn't get it to work for CHEM ENG 2I03 (2015/15-Term 2), but it would work for CHEM ENG 3D03 (2015/16-Term 1)...maybe it's a term selection issue?

**Comment by smiths** [comment]
Hello Sam.  Thank you for the feedback.  I am going to assign your comments as separate issues for @EvanVena and @bhancas.
