### ISSUE TITLE
Change status from submitted?

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#35]
@EvanVena how do I change the status of a report from submitted to not submitted?  Specifically, I would like to change the status of "Chem Eng Continuous Improvement Plan" for Chem Eng 2I03, 2013-2014, Term 2, so that it is no longer submitted.  This template was submitted by @SamGrimshaw .  Is this change in status possible?

**Comment by EvanVena** [comment]
Hi, @smiths @bhancas there is no way to edit the "Submitted" task, there only two options available are
1. restart that process but it will start again from the beginning.  
2.if there was a review step after that submission where the reviewer could reject the submission (we decided to remove this step)

**Comment by smiths** [comment]
We have had several issues related to this during testing.  The testers have inadvertently submitted work that they later wanted to change.  I think we should discuss whether we have any options to deal with this problem.

**Comment by EvanVena** [comment]
@smiths @bhancas 
with the new feature enable we can now do this.
Paused the process -->Log in as Manager --> right click on the task -->restart -->start the process
![image](https://cloud.githubusercontent.com/assets/20912011/20763531/6a3293ec-b6f8-11e6-9995-26d49a8e9fb6.png)

**Comment by smiths** [comment]
@EvanVena , it sounds like you are saying that we can keep the submit button and the submit feature.  A faculty member can then submit their work when they are done.  If they later realize they made a mistake, the task can be restarted.  Would this mean that they would lose the data that they previously entered?

**Comment by EvanVena** [comment]
@smiths  
yes, and they will not lose the data they previously entered.

PLUS: i have a way to disable the submit button without creating the dummy courses.

**Comment by smiths** [comment]
That sounds great Evan.  Better than what we were originally planning.  :-)
