### ISSUE TITLE
Warning in Instructor Manual for Step g "Submit"

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#38]
As discussed in issue #28 , can we please add a warning in the instructor's guide for the submission step.  Something to the effect, "Please make sure all data is complete before submitting.  This step cannot be undone."

Does the Vena interface give any kind of warning when the user selects Submit?  It would be nice to have a warning if possible

**Comment by JoeSpan** [comment]
Their should not be a submit option if you cannot "un-submit" the file. It is intuitive to submit the task after completion. Even with a warning in the instructors guide, this will happen again. I submitted two files I apparently should not have already. 
Joe

**Comment by smiths** [comment]
Good point Joe.  I will speak to @bhancas and @EvanVena about their thoughts on this during our next status update meeting.

**Comment by EvanVena** [comment]
Hi @smiths @JoeSpan the initial decided for the Vena has an approval process, and the approval process is used to control the submitted files  (for example, if you got rejected on the approval process, the files will rollback to you.)
