### ISSUE TITLE
Measured Indicators Do Not Align with Default Indicators on Display in the "Complete Rubric" template

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#39]
As stated by @SamGrimshaw in issue #34, 

Measured indicators did not align with the default indicators on display in the 'Complete Rubric' template. This wasn't an issue for courses that repeated the same indicators from the previous year, but many courses removed/added measured indicators to their respective course reports. I don't understand why the submitted 'CHEM ENG Measured Indicators' for a particular course/term combo did not affect the indicators on display for the same course/term in the 'CHEM ENG Complete Rubric'. I cannot add indicators listed in the complete rubric, which is sort of annoying. I would almost prefer having all the indicators shown, but selecting 0 or 1 at will in the 'use' column according to what was actually measured in the original course report. I'm already selecting 0 in that column when a particular indicator was no longer measured in one course offering.

@SamGrimshaw, could you give a specific example of a course where the Measured Indicators did not match the corresponding Complete Rubric template?

**Comment by EvanVena** [comment]
Hi @smiths @bhancas @SamGrimshaw 
The show/hide is based on the "Measured Indicators Input Template"
and this information is year sensitive.
(the current process is, when we start the new year, we always copy the data from previous year over, then you can manually adjust, but comparing with the data from couple years ago, measure indicator could be different)

for example. when you selected 2013-2014 Term 2 in the rubric, it is using the measure data from 2013-2014.

![image](https://cloud.githubusercontent.com/assets/20912011/18329649/8cc8201a-7522-11e6-9f96-e33c9776a051.png)

![image](https://cloud.githubusercontent.com/assets/20912011/18329658/96ac04ac-7522-11e6-87ee-dbd9ceb2a7b5.png)

**Comment by smiths** [comment]
Hello Evan.  What you describe is what I was hoping for.  In the original issue posting, I asked @SamGrimshaw  for clarification because I cannot tell whether the behaviour is a problem, or whether I inadequately informed Sam of what we are trying to do.  To get further specific information I asked Sam a question through issue #42 .

Sam is  unavailable until September 12th, so we will have to wait to see whether he observed a problem, or whether he was hoping behaviour that we don't plan on providing.

**Comment by smiths** [comment]
Given that so much time has passed, this issue will e closed.
