### ISSUE TITLE
Data tables will not always load

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#40]
As stated by @SamGrimshaw in issue #34, at times he had to re-check in because that data tables would not load.  I'm not sure how to reproduce this problem, but it is something we should keep an eye on.

**Comment by EvanVena** [comment]
maybe because i was doing something at the template at the same time.
if you see this again, can you please send me an email, so i can confirm.

**Comment by smiths** [comment]
Hello Evan.  Yes, I understand that it can be difficult to reproduce problems like this.  @SamGrimshaw , @JoeSpan and @zhengm2 , if you notice any performance problems, please post a specific issue about it.  Please list the specific course and what you are trying to do.
