### ISSUE TITLE
Can the Rubric Input Template Selection Interface Just list Courses?

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#43]
When I open a new Rubric Input Template to enter a course, I get a "Vena - Choose Pages" interface where one of the dimensions is Program.  Would it be possible for the dimension to be Courses?  My concern is that instructors will be confused because most (every?) course appears more than once in the Select a Members pane.  If each course was listed just once, it would be less confusing.

This interface may be a consequence of how the data is set up in the database.  If it isn't an option to just see the Courses, we'll just have to make sure that the instructors know that they can select any one of the instances of their course that appears.  That is, for this interface, they can ignore the program information.

**Comment by EvanVena** [comment]
@smiths @bhancas 
it is already setup that way, you have the option to change the display by clicking at the selected icon in the picture below. (the hierarchy icon)
![image](https://cloud.githubusercontent.com/assets/20912011/18329276/a2c6cfd0-7520-11e6-891f-b8587cadb2df.png)

**Comment by smiths** [comment]
Excellent.  I'll be honest, I had no idea we could do that.  I'll close this issue.

**Comment by smiths** [comment]
After the testing of @JoeSpan , I'm going to reopen this issue. Joe mentioned in his review of his testing that we don't really need the different degree options for Mech Eng.  In the system we need the different options, but not when one is selecting a course.  Can we make the view of the Program when selecting a Rubric show just the courses by default?  The default behaviour now is to show the full program choices, but a more logical default is to just list the courses.

**Comment by EvanVena** [comment]
@smiths  There is not option to list course only

**Comment by smiths** [comment]
will address in training
