### ISSUE TITLE
Faculty Review of Continuous Improvement Plans

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#46]
Can we add a very simple template to MEASURE?  The only purpose of the template would be for the Faculty to attach their annual report on their review of the departmental continuous improvement plans.  We already have a spot for the departments to upload (via comments) their reports.  In September of each year the Faculty will review the reports of the 7 departments and then generate their own report on the reports.  :-)

Maybe we can discuss this during our meeting on Friday (September 9).

**Comment by smiths** [comment]
I have updated the manuals in the repo to reflect a timeline that includes a faculty report.  For instance, the following document has been updated:

https://github.com/smiths/MEASURE/blob/master/McMaster%20Vena%20Admin%20Guide.docx

**Comment by EvanVena** [comment]
@smiths @bhancas 
I created the new template for the "Faculty Recommendations/Review", and I set the owner as @smiths  for now.

This template is allow faculty member to put it recommendations and attach the files, and i set this up at yearly level for now, if we need to go down to the term level, we can also do that.

Thanks
Evan

**Comment by smiths** [comment]
Looks good.  Yearly is the right way to go.  I'll close this issue.
