### ISSUE TITLE
Add Number of Students Measured to Course Report

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#48]
The Acting Associate Dean (Joe McDermid) has looked at the Course Report and he would like us to add the total number of students measured for each indicator.  He mentioned that the CEAB was looking for this during their last accreditation visit.  The charts show percentages, but Joe would like to see the total number of students as well.  If the number of students could appear somewhere in or near the chart, that would be great.

**Comment by EvanVena** [comment]
@smiths @bhancas 
Done!
![image](https://cloud.githubusercontent.com/assets/20912011/18447202/92fd56a6-78f3-11e6-9393-6345bad5aaa2.png)

**Comment by smiths** [comment]
Hello Evan.  Thank you for doing this.  Unfortunately, when I went to check the course report, the chart no longer seems to work.  I looked at Mech Eng 3M03 for 2013-2014, Term 1.  The column for total measured is there, but the chart doesn't show any data.  When I click to show the summary chart I get the following message from Microsoft Visual Basic "Run-time error '1004': Application-defined or object-defined error"

**Comment by EvanVena** [comment]
Hi Spencer,

this is fixed.
there are lots of calculation a the course report, when i added a column,
some of the calculations referencing to the wrong cells, and causing this
issue to happen.

can you try again?

Thanks
Evan

**Comment by smiths** [comment]
Hello Evan.  Unfortunately I no longer see any data in the Course Reports.  I looked at 2013-2014, Term 1 for Mech Eng 3M03, 2013-2014, Term 1, Mech Eng 4R03 and 2014-2015, Term 1, Mech Eng 4Q03.  All of these files listed the indicators measured an nothing else.

**Comment by EvanVena** [comment]
Hi Spencer,
can you check, if you are picking the right section? i believe you are
looking at section 1.
and i can see some data.
[image: Inline image 1]
Thanks
Evan

**Comment by smiths** [comment]
Thank you Evan.  You were correct.  I was looking at the wrong section.  I always leave the section set to 1, but somehow I must have inadvertently clicked on section 5.  Unfortunately I have proven once again that looking in the wrong place for data is a very easy mistake to make.

With respect to the current issue, everything looks fine!  The charts look good and the total number of students measured shows up.  I'm going to go ahead and close this issue.
