### ISSUE TITLE
Concurrent Access of Rubrics?

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#49]
In issue #9, @JoeSpan mentions that he could not access one of the Mechanical Engineering rubrics (4M06) because it was currently protected.  The message said that Spencer Smith had the rubric open.  I did not have the 4M06 rubric open, but I did have the 3K04 rubric open.  Will we have a problem that instructors will not be able to concurrently enter data on different courses?

**Comment by JoeSpan** [comment]
This is what I got when trying to open the Mech Eng Complete Rubric
![image](https://cloud.githubusercontent.com/assets/20819724/18364977/a677933a-75de-11e6-877c-9e747ed6301e.png)

**Comment by smiths** [comment]
Hello Joe.  I just checked in my version of the file.  Can you now open it?

**Comment by JoeSpan** [comment]
Now I can open it. Thank you.

**Comment by EvanVena** [comment]
Hi @smiths @JoeSpan 
it allows concurrent user. 
However we do see it happens sometime. you can force check in the files by following the follow process
Issue Summary:
A task has been checked out by a user who is unavailable and it needs to be checked back in.

 

Suggested Solution:

- Login as a manager

- Go to Status Tracker

- Find the checked-out task assigned to the user

- Right click on the status of the task and hit Force Check-In

 

*Please see the screenshot below to help navigate

**Comment by EvanVena** [comment]
![image](https://cloud.githubusercontent.com/assets/20912011/18367414/f5807f00-75e8-11e6-95d3-a453547fa8c4.png)

**Comment by smiths** [comment]
Thank you for the information Evan.  Do you think you could add the description of a Forced Check-in to the Administrators Guide?
