### ISSUE TITLE
Remove Terms 4 and 5

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#52]
I have confirmed with the Assistant Dean (Maria White) that we do not have a need for measuring Terms 4 and 5.  To simplify the interface, we should remove those options.  We discussed the issues around this in issue #26 .

**Comment by EvanVena** [comment]
@smiths @bhancas 
Done!

**Comment by smiths** [comment]
Thanks Evan.  This has definitely helped with cleaning up and clarifying the interface.
