### ISSUE TITLE
Move rubric created in wrong term?

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#53]
If an instructor fills in a rubric for the wrong term, can that rubric be moved to the correct term?  For instance, @JoeSpan added 3M03 for 2013-2014, Term 1, but he meant to add the course for Term 3.  Do we need to create a 3M03 for 2013-2014, Term 3 and manually copy the data over?  If we did this, is there a way to delete the Term 1 entry?

Mistakes in term are likely, both for creating data and in looking for data.  Is there any way to reduce the likelihood of these mistakes?

**Comment by EvanVena** [comment]
@smiths @bhancas 
I think the best option will be manually copy the data from Term1 and enter into th Line item detail in Term 3 then delete the entry on Term1.

**Comment by smiths** [comment]
Thank you Evan.  Is it possible to delete a course rubric?  If so, how is this done?

**Comment by EvanVena** [comment]
Hi Spencer,

you can follow the instruction below.
select the line item detail you want to delete --> under the Vena tab in
excel -->find the  line item details section-->click "Remove"

[image: Inline image 1]

Thank you
Evan

**Comment by smiths** [comment]
Okay  Evan.  I will ask @JoeSpan to test adding and deleting a rubric.
