### ISSUE TITLE
Historical Program Measurement Report Not Showing for Mech Eng 3M03

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#54]
@JoeSpan has entered data for Mech Eng 3M03 for 2013-2014 and 2014-2015, but the historical report only shows one data point.  Is this because we haven't archived the data, or because 3M03 was entered for different terms?

We also have two years worth of data for Mech Eng 4R03 and Mech Eng 4Q03, but each of these also only show one year (2014-2015) worth of data.  In this case both courses had data entered for the same term.

**Comment by EvanVena** [comment]
@smiths @JoeSpan @bhancas 
This is because of two reasons.
1. the starting year of the report is 2014-2015 ( I already reset the start year to 2013-2014)
2. We haven't archive the data, the program data only show up, after the archive process.

The data are showing at the "Historical Course Measurement Report", if you want to check if the data is in the system or not, this should be the place to go.

**Comment by smiths** [comment]
Hello Evan.  Yes, I can see the data now in the Historical Course Measurement Report.  Very nice!  Can you confirm for me that this report does not care which term a course is offered in?  If 3M03 is offered in Term 1 one year and Term 3 the next year, all the data will be included in the plot, right?

I have a minor concern about how the data is displayed that I will post in a new issue.

**Comment by smiths** [comment]
I have added a note to the Admin Guide (as found in commit 980a2db ) to explain that the reason for archiving the data is so that we can generate the program measurement reports.

**Comment by EvanVena** [comment]
Hi Spencer,
regardless of the terms, it will aggregate to the academic year level.

Thanks
Evan

**Comment by smiths** [comment]
Great!  Maybe this means we don't need to worry too much about errors with an instructor entering the wrong term?  It will be a problem when a course is taught in both terms, but in those cases the instructors will be aware of the other term and will likely be more careful.  It will also be a problem when someone is looking for a course report for a certain year and term combination and it doesn't exist.  I'm still not sure what we do in that case.

**Comment by EvanVena** [comment]
Hi Spencer,
i don't think it will be issue for the course report. since the course
report is at the term level.
but the historical course measurement report is at the year level.

Thanks
Evan

**Comment by smiths** [comment]
Since the reason for the data not showing in the historical program measurement report is now explained, I will now close this issue.  We are having a separate discussion about ways to remove the problem of instructors entering data in the wrong term.
