### ISSUE TITLE
Chem Eng Continuous Improvement Plan Task Name associated with Course Report?

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#55]
For Chemical Engineering the Task "Chem Eng Continuous Improvement Plan" is associated with the Task Form "Course Report."  Is this correct?  The name seems confusing to me.

**Comment by EvanVena** [comment]
@smiths @bhancas 
Hi, yes, you are right,
We decided to use the course report as data entry form to the continuous improvement process.

**Comment by smiths** [comment]
Hello Evan.  I'm still confused.  What is the name of the task for generating the continuous improvement plan?  In the graphical view under Manager/Designer, I do not see a spot for the continuous improvement plan.  How does the continuous improvement committee get their report into MEASURE?

**Comment by EvanVena** [comment]
Hi Spencer,
there are two continuous improvement input in the process.
1. from continuous improvement committee, this is an independent process in
the graph interface, please see the highlighted below.
[image: Inline image 1]
2. from instructor, this is enter via course report.
[image: Inline image 2]
Thanks
Evan

**Comment by smiths** [comment]
I cannot see your images Evan, but the words have helped to some extent.  I think in our next meeting we should go through who does what and when.  I also think we should think whether the instructors need to do a course rubric and a course report.  This is causing confusion for the testers, and it also muddies the waters on the continuous improvement phase.

**Comment by EvanVena** [comment]
are you using outlook?
Outlook will not automatically download image, at the upper section under
receiver's name, you should see a message "Click here to download pictures".
if you click it, you should be able to see the pictures.
Thanks

Evan

**Comment by smiths** [comment]
Hello Evan.  I do not use Outlook.  Moreover, I do not use an e-mail program to view your messages.  I'm using the GitHub issue tracker interface (web interface at https://github.com/smiths/MEASURE/issues).  I think if you look at the GitHub page, you will see that your images do not show up there.  It usually isn't a big deal, but when your images do come through, they are very helpful.
