### ISSUE TITLE
Add Projects and Presentations to Measurement Category in Rubric Template

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#56]
As @JoeSpan mentioned in issue #50, we should add two items to the drop down suggestions for "Measurement Category" in the "Rubric Input Template."  Specifically, we should add the options "Projects" and "Presentations."

**Comment by EvanVena** [comment]
@smiths @bhancas 
Done.
![image](https://cloud.githubusercontent.com/assets/20912011/18440560/9ccf5f4c-78d7-11e6-9ac7-ccb094638519.png)

**Comment by smiths** [comment]
Great!  Thank you Evan.
