### ISSUE TITLE
Historical Report Shouldn't plot unmeasured years

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#57]
The "Historical Course Measurement" for Mech Eng 3M03 is currently confusing to read.  As mentioned in issue #54 , I have a bit of a concern with it.  We really shouldn't plot the data for the unmeasured years.  If one looks at the plot quickly, it appears that exceeds expectations (for instance) is dropping in 2015-2016.  This isn't really the case.  It is just a consequence of the fact that that year hasn't yet been measured.

For the Historical Course Measurement, could we just show the data that has been measured?

**Comment by EvanVena** [comment]
addressed, only year has value are showing up.

**Comment by smiths** [comment]
Hello Evan.  I looked at Mech Eng 4R03 and the years with 0%s are still showing up.

![histcoursemeasures](https://cloud.githubusercontent.com/assets/1422000/18451260/2e9d2798-7904-11e6-9f43-a5526f9c2f70.jpg)

**Comment by EvanVena** [comment]
Hi Spencer, there are two of them
i fixed the program one.

i also fixed the course one now, can you please check.
[image: Inline image 1]

Thanks
Evan

**Comment by smiths** [comment]
Yes, I can see that the plots no longer contain the data for the unmeasured years.  Great!  I am going to go ahead and close this issue.
