### ISSUE TITLE
Move 3M03 for 2013-2014, Term 1 to Term 3

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#58]
In issue #53 @EvanVena describes how to move a rubric from one term to another.  Could you please try following his steps to move the Term 1 data to Term 3 for 3M03, 2013-2014.  I imagine that this will be tedious, but I would like your impression.  I think this case of entering data in the wrong term might come up again, and I would like to have an idea of how much trouble it is to fix an incorrect data entry.  This will also help us answer the question on whether or not we want to fix it, or whether we should just accept that some data is in the wrong term.  :-)

**Comment by JoeSpan** [comment]
Okay, so I'm not sure if I am understanding this correctly. Are these the steps you would like me to follow @EvanVena 
1. Open 2013-2014 file term 1
2. Copy one line item
3. Close 2013-2014 file term 1 and check in
4. Check out 2013-2014 file term 3
5. Insert line item
6. Paste data for that line item
7. Close 2013-2014 file term 3 and check in
8. Check out 2013-2014 term 1
9. Delete the first line item. 
10. Repeat for all line items
The total cycle time for one item I estimate is in the order of 10-20 min as each checkout takes a few minutes to load. Considering their are 32 line items (8 sets of 4) this would take hours to complete. I can proceed but their must be a better way. 
@smiths What do you think?

**Comment by EvanVena** [comment]
Hi Joe,

yes as always, there are two ways to do it. one was describe above.
second is using the ETL process to alter/delete the line item detail (i am
not suggesting to do it this way, there is risk involve, potential
can affect other line item detail as well as the database behind it).
you can reference the link below for more information about line item
detail.

http://docs.vena.io/etl-guide/data-integration/#line-item-details

Hope this help.

Thanks
Evan

**Comment by smiths** [comment]
Hello Joe.  I retract my original request.  I no longer want you to do this issue.  The time required is far too long.  I have spoken with @EvanVena and @bhancas and we have a plan that should make it very difficult for someone to enter the data in the wrong term.  I think eliminating the possibility of putting the data in the wrong place is better than fixing the error after the fact.

Thank you for the information @EvanVena .  You have confirmed that solving this problem after the fact is unrealistic for us at this time.

I am going to close this issue.
