### ISSUE TITLE
Add Joe for Mechanical

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#6]
We need to add Joe Span as a contributor to MEASURE.  This means first adding him using the options available under the Admin tab.  We first need to create his account of the contributor type, and then add him as a contributor under Permissions.  Joe's information is as follows:

Name: Joe Span; e-mail: spanjh@mcmaster.ca

We then need to add Joe as a User for the curriculum mapping and measured indicators and for the rubrics associated with mechanical.

Michelle, if there are any problems or questions, please enter comments below.

**Comment by zhengm2** [comment]
Hi Spencer,

I have added Joe as an user and I will email him with the password and login. Did he sign up for GitHub yet so that I can assign or forward this to him?

**Comment by zhengm2** [comment]
Hi Spencer,

I have added Joe as an user and I will email him with the password and login. Did he sign up for GitHub yet so that I can assign or forward this to him?

**Comment by smiths** [comment]
Hello Michelle.  Joe was away last week, so I do not believe he has seen my e-mail requesting he register for GitHub.  I just sent him another request.

**Comment by smiths** [comment]
Actually, you should e-mail Joe his password and login.  The discussions are public, so we don't want to post passwords here.  :-)

**Comment by zhengm2** [comment]
Hi Spencer. I emailed it to him yesterday but have not heard back yet. Once he has confirmed that he has access I will close this issue.

**Comment by smiths** [comment]
Joe is added now.
