### ISSUE TITLE
Description of Forced Check-In to Admin Guide

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#60]
Hello Evan.  Can you please add a description of how to do a forced check-in to the Administrator's Guide.  We discussed this as part of issue #49.

If possible can you start from the version of the Admin guide at 

https://github.com/smiths/MEASURE/blob/master/McMaster%20Vena%20Admin%20Guide.docx

This version is up to date with all of your edits and it has a few minor ones from me.

You don't need to resubmit the file to GitHub.  I can take care of that if you e-mail it to me.

**Comment by EvanVena** [comment]
[McMaster Vena Admin Guide_20160916.docx](https://github.com/smiths/MEASURE/files/477175/McMaster.Vena.Admin.Guide_20160916.docx)

@smiths @bhancas

**Comment by EvanVena** [comment]
Please see the updated document above

**Comment by smiths** [comment]
Hi Evan.  I see the document now.  I have taken this version and used it to push a new version to the repo.
