### ISSUE TITLE
What needs to happen to reach "Curriculum Committee Recommendations Input"

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#61]
It is unclear to me what needs to happen to reach the "Curriculum Committee Recommendations Input" template.  I was looking at My Tasks in the role of Contributor, and I don't understand why some tasks have the status "Not Reached."  I'm not saying that they should have a different status; it is more a case that I don't understand what needs to happen for the status to change.

**Comment by EvanVena** [comment]
@smiths I made this part of the initial process, so it will start when the process start

**Comment by smiths** [comment]
I have verified that I can see the template from the start.  I will close this issue.
