### ISSUE TITLE
Does anything in the spreadsheet change when a comment is added?

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#62]
I have been testing adding a comment for the continuous improvement plan and this has led to a question.  Should anything change on the template when a comment (File) is attached?

**Comment by EvanVena** [comment]
@smiths because the comment is tied to the cube (data model) nothing in the excel sheet will change

**Comment by smiths** [comment]
I have updated the Contributor's Guide for the Department (in commit 3a3c9fb) to explicitly state that the user should write something in the cell, so that future readers know that a comment is attached.   

@EvanVena , if you edit the Contributor's Guide, please use the version in the repository.  You can find it at:

https://github.com/smiths/MEASURE/blob/master/McMaster%20Vena%20Contributor%20Guide%20-%20Department.docx
