### ISSUE TITLE
"Curriculum Committee Recommendations Input Template" Test

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#63]
Hello Joe.  Can you please check to see if you can see the ""Curriculum Committee Recommendations Input Template" for Software Engineering in 2014-2015?  If you can open the template, can you please check to see if you can see a file (as a comment) under the Software Engineering (BEng) Recommendations.  I attached a report, but I want to make sure that other scan see it.

You have been assigned the template, so it should appear under "My Tasks."  However, it might have the status "Not Reached."  I am asking @EvanVena what conditions cause this status to be changed.

**Comment by JoeSpan** [comment]
Yes @smiths, I successfully opened the template, The status was "work in progress" for me so I had no problems. Looks like "•	All course report data must also be uploaded to the VENA database run by the Faculty, starting in 2015/16 and for all subsequent years." Sounds like a good plan. 
Note: It is not intuitive that their is a file hidden. 
![image](https://cloud.githubusercontent.com/assets/20819724/18885768/13499c0c-84bb-11e6-8081-e5cb8f451be9.png)
The hint helps but I do not see the point of having a cell containing just a giant zero. Is it possible to change the contents of this cell to be the comment/instructions? Once I saw it, I had no problem. Total time to figure this out was about a minute so it was not really terribly difficult.

**Comment by smiths** [comment]
Thank you Joe.  I discussed the issue of not being able to see when a comment has been added with @EvanVena ( #62).  Vena does not show that there is a comment, so I added a note in the contributor documentation for contributors to explicitly put text in the cell to point to the attached comment.  I've changed the curriculum committee recommendations report for software engineering (2014-2015) to include some text in the cell.  Can you please verify that you can see this text?

**Comment by JoeSpan** [comment]
So something strange is happening right now. I can check out the file, but the macro's to chose both the year and the program are not appearing. I get the chemical engineering 2013-2014 document. @SamGrimshaw , did you have the curriculum committee recommendations file open at 1:31 pm on September 28th? @smiths if this persists, we might need to open another issue regarding this. 
For the 2013-2014 chem eng report I do not see any text in the file, I will check back later, hopefully the macro's are working then, to test the software 2014-2015 report.

**Comment by smiths** [comment]
I did have the file checked out, but it was checked in before I posted on GitHub.  You won't see any text in the chemical engineering report, since I didn't add any.  It is only the software engineering report that I modified (for 2014-2015).  Please try again.  I'll also look into whether we need a forced check in. (Instructions for a forced check-in are given in the administrators manual.)

**Comment by smiths** [comment]
Hi @JoeSpan .  I'm still looking into it, but you are the one that has checked out the file.  Can you look at your status tracker and click on the "Curriculum Committee Recommendations Input" task.  You should be able to click Check In.

**Comment by smiths** [comment]
Hi @JoeSpan.  I just did a forced check-in of the curriculum committee recommendations report.  Essentially I checked it in for you.  Can you try again now to look at the software engineering report for 2014-2015?

**Comment by JoeSpan** [comment]
@smiths I just tried it again, and I am still having the same problem. I did forget to check in the file a couple days ago and had issues checking it back in. It is possible this is the reason. Is their a way for me to force check in a file? I remember this topic but I think you need to be a manager to do it.

**Comment by JoeSpan** [comment]
@smiths I just did a good old fashioned windows reboot and I have re-gained functionality. I think the system does not like it when you do not check in files for days. I was successfully able to see the software eng 2014-2015 but their isn't any text in the document. The only data is the word document.

![image](https://cloud.githubusercontent.com/assets/20819724/18926528/1cad1a00-8586-11e6-87d5-6f760630e1e7.png)

**Comment by smiths** [comment]
Hello Joe.  I'm glad to hear that you were able to access the document.  I have reproduced your result of not being able to see the text that I entered in the recommendations field.  When I open the template, I do not see it either.  I am going to post an issue for @EvanVena .

**Comment by smiths** [comment]
@JoeSpan, with respect to your question about forced check-in, you are correct that only managers can do that.  If you ever have this problem again, please let me know.  @zhengm2 is also a Manager, so she can also do a forced check-in.

**Comment by smiths** [comment]
This issue has been resolved.
