### ISSUE TITLE
Is the "Input Variables Template" Under Data Controls?

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#64]
Is the "Input Variables Template" Under Data Controls, or is it under McMasterTemplates?  The different versions can be found under Manager/Files  Library.

**Comment by smiths** [comment]
The Admin Guide shows the file is in Data Controls.  However, I will leave the issue up, since I would like clarification on why there are two versions of the file.

**Comment by smiths** [comment]
The input variables template still appears under Data Controls and under McMaster Templates for me.  @EvanVena indicated that it sometimes takes some time for changes to be reflected on client machines.  I'll wait and check this issue again in the future.

**Comment by EvanVena** [comment]
@smiths  can you please check again now?

**Comment by smiths** [comment]
It's gone now!  Thank you Evan.  I'll close this issue.
