### ISSUE TITLE
Restrict availability to only valid courses

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#66]
Not all course, term, section combinations are valid.  As the system is now, an instructor can add data for a section of a course that does not exist, or for a term when the course is not offered.  Similarly others might look to read data on a course and select a term when it isn't offered and thus erroneously think that no data has been entered.

@EvanVena and @bhancas discussed using a file consisting of the following data to restrict the data entry options:
course identifier, terms offered, sections offered.

Maria White is currently building this file.

**Comment by EvanVena** [comment]
Hi @smiths 
Currently the best option i can came up with is putting the validation rule.
Vena doesn't have the option to limit the dimensions.
![image](https://cloud.githubusercontent.com/assets/20912011/18843595/ab592fa0-83e7-11e6-924c-14fd680fb643.png)

Hope this help,

**Comment by smiths** [comment]
Thank you for the information Evan.  This makes sense.  I would prefer if the option wasn't even available, but I'm okay with your solution.  The warning will be a big improvement and prevent most errors.

Maria White (Assistant Dean) is currently working on the list that summarizes courses, the terms they are offered and the sections that exist.

I'll close this issue once we get a chance to test it.

**Comment by smiths** [comment]
Discussion moved #89.
