### ISSUE TITLE
Names of instructors

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#67]
There is a report in MEASURE that includes the data on which instructors are teaching which courses.  Please add how to edit this file to the Admin Guide.

**Comment by EvanVena** [comment]
@smiths  Updated, please see the attached document.
[McMaster Vena Admin Guide.docx](https://github.com/smiths/MEASURE/files/493752/McMaster.Vena.Admin.Guide.docx)

**Comment by smiths** [comment]
Hello Evan.  Unfortunately you updated the wrong version of the admin guide.  In the previous draft you added Forced Check in, but in the current version you no longer have that content.  Can you please use the version in the repo when you make changes?  You can always find the most recent version at:

https://github.com/smiths/MEASURE/blob/master/McMaster%20Vena%20Admin%20Guide.docx

I also make minor changes on occasion, which I have to redo to your version when you don't use the latest one.  I will manually add your section 10 to the repo version.  The latest commit (4c66f2a) holds the combination of the last Admin Guide you sent and the one that was currently in the repo.

If you make any edits to the manuals, please start with the version in the repo.   You can either e-mail the revised version to me, or post it in a comment as you did above.  I'll make sure to update the repo version.

If you have any questions, please let me know.

**Comment by smiths** [comment]
I'll test whether I can update the list of instructors and then close this issue.

**Comment by EvanVena** [comment]
@smiths I am sorry, i must have so many different version on my computer.

**Comment by smiths** [comment]
No problem Evan.  It is very hard to keep track of different versions.  That is why I recommend using git for version control.  Git keeps all of the old versions, in case you need them, but usually it is just the last version you need.  If you get the file you plan on editing from this web-page and send it to me when you are done, I'll make sure it is updated via git.

I'm sure you don't have time, but if you are ever interested, I have worked with one of my teaching assistants to build a short introductory lab exercise for git.  I'll attach the exercise, just in case you have time.  :-)

[Lab03.pdf](https://github.com/smiths/MEASURE/files/494516/Lab03.pdf)

**Comment by smiths** [comment]
The template opens, so I am going to close this issue.  However, I am going to add a future enhancement to make it easier to update this information.  I do not think the departments will take the time to type this all in manually.  I would guess that there is a quicker way, so using a file with the information summarized as input.  This isn't important enough to take up our valuable time now, but it might be nice in the future.
