### ISSUE TITLE
Text Entered into Curriculum Committee Recommendations Input Disappears

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#68]
Hello Evan.  @JoeSpan and I have been testing the Curriculum Committee Recommendations Input Template (issue #63 ) and we have found an apparent problem.  I have been testing the template for Software Engineering, 2014-2015.  I am able to attach comments to the cell below "Recommendations for Software Engineering (B.Eng.)," but I am not able to save the text I enter into this cell.  I checked out the template, attached a comment, edited the cell, saved the file and checked it back in.  Everything seemed to work fine, but now when I open the same template I do not see the text that I entered into the cell.  The attached comment is there, but the text is not.  All that appears is a zero (0).

Do you have any idea why this might be the case?

**Comment by smiths** [comment]
As a follow-up, I tried adding text to the same template for the entry next to MATH 2Z03.  This worked fine.  When I opened the template again, the text was persistent.  The problem might only exist for the cell below "Recommendations ...".

**Comment by EvanVena** [comment]
Hi, @smiths @bhancas @JoeSpan 
This is a bug in the design, and I already fixed this issue, can you please check again?

Evan Situ

**Comment by JoeSpan** [comment]
I just tried the software 2013-2014 template. Their is now text in the field. Thank you @EvanVena whatever  was done seems to work on my end. 
Joe

**Comment by smiths** [comment]
I have also verified that the behaviour has been fixed.  Thank you @EvanVena .  I'll close this issue now.
