### ISSUE TITLE
Any way to monitor what course rubrics are complete?

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#69]
Since we are moving to remove the submit button, will there be any simple way to monitor which courses have had the rubric information added?  I know we might have to sacrifice this, but it would be nice during to term to know which instructors have completed their course reports and which haven't.  Opening each of them to see if it is filled in isn't feasible.  I'm wondering if there is a simple report that can be generated based on the data in the rubrics.  If the data is filled in, we know the rubric is complete.  If it isn't filled in, we know that is an instructor we have to chase after.

Maybe we can discuss this during our meeting on Monday?

**Comment by EvanVena** [comment]
I think the best way is creating a simple report to aggregate the Rubric information.
but it is almost impossible to check whether or not the Rubric information is complete, an instructor can enter couple lines of Rubric information, and we can't really tell.

in the data side, all we can track is whether there are information/data in it or not.

**Comment by smiths** [comment]
How difficult would it be to do what you describe @EvanVena?  I like the idea of at least knowing whether an instructor has started their data entry.  Most of the time, if they have started, then they will have finished.  I know an instructor could fake it that they completed their work, but they don't know that we can't tell.  :-)

**Comment by EvanVena** [comment]
It is not so difficult to do, i think i can do it in about 1 hour.
Please let me know, if you like to build it.
Evan

**Comment by smiths** [comment]
Hello Evan.  If we are going with Plan A (where we use the new version of Vena's software), I would like this work done.  If we are going with Plan B (where courses are assigned to instructors and the submit button is enabled), then we don't need it.  We have a call scheduled for tomorrow (Nov 2); we can discuss this option at that time.

**Comment by smiths** [comment]
Hello Evan.  I discussed this issue with Bogdan.  We agreed that creating a report that summarizes whether someone has entered any data in their rubric is worthwhile.  Therefore, in answer to your earlier question, Yes, I would like you to build this report.  Thank you!

**Comment by EvanVena** [comment]
@smiths @bhancas 
added new report called "Rubric Entry Report"
to show the status of Rubric entry

**Comment by smiths** [comment]
Hello Evan.  This looks like a great start.  This kind of information will be very valuable for monitoring the status of our data entry.  However, there are some strange numbers.  For instance, for ENGINEER 1P03, 2014-2015, Term 1, Section 1, there are over 4000 students that meet expectations.  What does this mean?  As far as I can tell no indicator or attribute has been selected.  How is there a number for meets expectations?  It would be great to have a meaningful number here.  Could we average the percentages of students in each category for each indicator?  This would be like an "average" metric for the course.  It wouldn't be exactly meaningful for the CEAB, but it would be neat to have.  If it isn't easy to create, that is fine, but any kind of summary information that is easy to grab would be wonderful in the Rubric Entry Status screen.

**Comment by EvanVena** [comment]
@smiths 
This number is the sum of all attributes,
for example if you have 13 attributes with each attribute has 3 indicators you want to measure.
and if you have 50 students,
so the math will be 13 * 3 * 50 = 1950

Because we are using the concurrent contributor, we agreed on to monitor when the instructors started to enter information into Rubric.

Thanks
Evan

**Comment by smiths** [comment]
I'm not sure how useful the number you are proposing is, but having a summary of which templates are populated is great!  Now that the submit button has an unsubmit, does that mean that the status tracker can give us the same kind of information?

**Comment by smiths** [comment]
@EvanVena will modify the template so that it doesn't show the meaningless numbers.  @zhengm2 , we will need to add documentation to the Admin Guide on how to use this template.

**Comment by smiths** [comment]
This information has been added to the admin guide.
