### ISSUE TITLE
Add Eng 1 Courses to All Programs

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#7]
At the moment each degree program only includes the courses from second year on.  We need to add the first year courses too.  This is a good test case for the Admin User Guide.

Michelle, can you please add the Eng 1 courses to the program for one of our degree options?  If your test shows that the steps are too tedious, then we could ask @bhancas and @EvanVena if there is a quicker way to make the changes on their end.

Please let me know if you have any questions.

**Comment by smiths** [comment]
Adding the first year courses to each degree program might be a Go Live issue, so I'm going to assign this issue to Bogdan as well.

**Comment by smiths** [comment]
I discussed this with Evan today (Sept 2) and we don't have to wait to make the changes.  Adding Eng 1 to our programs is a good test case.

**Comment by zhengm2** [comment]
@smiths I followed the steps and it does not seem tedious as it's simply copy and paste. However, it looks like Eng 1 has been added to all of the engineering programs.

**Comment by zhengm2** [comment]
@smiths On closer inspection Eng 1 has not been added to all programs. @bhancas is there a way to copy Eng 1 to another program? With the instructions currently using 'Cut' or even drag and drop it removes it from the Eng 1 folder.

**Comment by EvanVena** [comment]
you can try to use the "Share" on the member, basically follow the steps
below
[image: Inline image 1]

**Comment by smiths** [comment]
Thank you for the advice Evan.  Unfortunately the image did not come through in your last comment.  Could you please re-post it?  I tried to see what I can do for editing the courses, but with a virtual version of Windows on my Mac, I cannot find a way to send a right mouse click.

**Comment by smiths** [comment]
@zhengm2, have you had a chance to try the Share option mentioned by @EvanVena ?

**Comment by zhengm2** [comment]
Thanks @EvanVena for the instructions. Share and Paste does work for individual courses. @smiths it's simple to do but a little tedious as it needs to be done one course at a time. I can finish this off with the remaining programs as we just need to set it up once.

**Comment by EvanVena** [comment]
This can also be done in an ETL process, i will have to write some SQL code
to do that, it will take at least a day or two to do.
I suggest we can put this as an enhancement feature.

Thanks
Evan

**Comment by smiths** [comment]
@EvanVena , I do not think we will need an ETL process, as this task should only have to be done once.  Once we have Engineering 1 set-up properly, every year should just copy the previous year.

@zhengm2 , that is great that you are able to edit the courses and fix the curriculum.  We should make sure that your efforts are reused.  At this point, the only year we need to be accurate is 2016-2017 (this current academic year).  If we don't have it already, could you please create it.  When you are fixing the Eng 1 curriculum you can then do it in 2016-2017.  The other option is to fix it in the current year and have the changes rolled over into the new year.  My only concern there is that I'm not sure which year the current year will be based on.

@EvanVena , what is a quick way for us to see what the current year is?

**Comment by smiths** [comment]
We can update the Eng 1 curriculum for the 2015-2016 Term 2 data (as given in the global variable).  When we create the 2016-2017 academic year, this data will roll over.

@zhengm2 , would it help to ask another administrator to help with copying Eng 1 to the other programs?  This would be a good test case.

**Comment by smiths** [comment]
When we create the 2016-2017 year (issue #74 ) we'll need each department to update the Eng 1 curriculum.  We'll need to make sure that the documentation on how to do this is clear in the departmental contributors guide.

**Comment by zhengm2** [comment]
Hi Spencer,

This was completed a while ago so I will close this issue.

**Comment by smiths** [comment]
Yes, good to close up our old issues.
