### ISSUE TITLE
Import Instructor Information

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#70]
In the future, it would be nice to have a simple way to import the information for the "Course Info Maintenance Template".  It is unlikely that departments will invest the time to enter this information manually.  Hopefully there would be a way to do this using a file with the information stored in it.  This issue came up as a consequence of looking through issue #67.

**Comment by arana2** [comment]
@smiths, I currently do not see the "Course Info Maintenance Template" as an active template.  Do we know if this has been deprecated?

![image](https://user-images.githubusercontent.com/38359810/46678477-b4a30580-cbb2-11e8-952e-c29489657db6.png)

![image](https://user-images.githubusercontent.com/38359810/46678312-5ece5d80-cbb2-11e8-93bc-69bd24f3fb98.png)

**Comment by smiths** [comment]
The Course Information Input Template was never really used.  We discussed capturing other relevant information on each course in Vena, but it never really went anywhere.  You could definitely delete this template.  It doesn't have anything useful in it.

**Comment by arana2** [comment]
Thanks @smiths!

- Closing Ticket
- Confirmed this template is no longer active
- Moving template to Archive Folder

![image](https://user-images.githubusercontent.com/38359810/46680361-e4eca300-cbb6-11e8-8c0c-09c8736eefda.png)
