### ISSUE TITLE
Write access to curriculum mapping and measurement mapping?

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#75]
I'm not sure how it is currently set up, but can we restrict the write access to the curriculum mapping and measurement mapping, but allow everyone read access?  I believe we can do this by having the associated reports available to everyone, but restricting who is assigned access to the input templates.

**Comment by EvanVena** [comment]
@smiths  
The currently setup should be all the templates have read and write access,
all the report should only have read access
with the exception of the courses report.

**Comment by smiths** [comment]
Great!  Your explanation matches what I was hoping to hear.  I will close this issue.
