### ISSUE TITLE
Warning for wrong year only comes up when saving

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#76]
Is it possible to have the warning that someone has selected the wrong year when they open a Rubric (or other templates) instead of (or in addition to) when they save?  I worry that someone will invest the effort to fill in a template and only find out when they are about to save that the effort has been wasted.

**Comment by EvanVena** [comment]
unfortunately the Vena Validation rule will only run before you save the data,
for safety purpose, I can add the message as highlight on the top, please see the picture below.
This update is on the template "Rubric Input Template with new validation rule on course offered"

hope this help.

![image](https://cloud.githubusercontent.com/assets/20912011/19574096/c6bada12-96d6-11e6-937d-764d1336607c.png)

**Comment by smiths** [comment]
Yes, the red background warning will be fine.  Thank you.
