### ISSUE TITLE
Rubric Input Template Measurement Date Format

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#78]
In the "Rubric Input Template" the Column for Measurement Date has a hint for the format in the form of =Today().  Could we instead make the hint dd/mm/yyyy?  The problem with the hint is that for a date like today 10/12/2016 it is ambiguous.  Is it for October 12 or December 10th?

**Comment by EvanVena** [comment]
Hi @smiths 
make the hint dd/mm/yyyy will not be efficient, since base on the different computer setting, the mm, dd and yyyy can be at the different place.

that's how we setup before, but it ran into problem for different computer setting, that's why we changed to this.

@JoeSpan 

Thanks
Evan

**Comment by smiths** [comment]
This makes sense, but could we edit the title to make it clear that the date is today's date?  Neither I nor the Associate Dean realized this at the time.  Maybe we can mention "today =" in the text of the heading?

**Comment by EvanVena** [comment]
Added
![image](https://cloud.githubusercontent.com/assets/20912011/19821806/6271ca4e-9d2e-11e6-9761-75bdb16fed50.png)

**Comment by EvanVena** [comment]
Done.

**Comment by smiths** [comment]
Looks good.  Thank you Evan.  I'll close this issue now.

**Comment by arana2** [comment]
Re-opening this ticket as the date discrepancy was raised during the end-user meeting.  Will need to see if the rubric input template can apply a consistent date format.
- Andrew will raise this during the training session.

Measurement Date Format: YYYY-MM-DD
![image](https://user-images.githubusercontent.com/38359810/48207474-b6412400-e33e-11e8-9dcf-9b052e0315fa.png)

Rubric Input Template – Input Format: YYYY-MM-DD
![image](https://user-images.githubusercontent.com/38359810/48207554-dcff5a80-e33e-11e8-9c90-f914124bf24d.png)

Rubric Input Template – Display Format: DD-MM-YYYY

![image](https://user-images.githubusercontent.com/38359810/48207572-ec7ea380-e33e-11e8-8b31-61d0ed165f70.png)

**Comment by smiths** [comment]
@arana2, good thinking to find the old issue related to this.  😄 I am confused by the behaviour, since the command today displays different from how the dates display elsewhere.  This seems like an Excel issue.

**Comment by arana2** [comment]
Closing issue as it has been resolved,
