### ISSUE TITLE
Revise McMaster Vena Department Contributor Guide

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#79]
Hello Michelle.  Please revise the Department Contributor Guide so that we are prepared for rolling out to the departments for the first week of November.  Our first step is to get all departments to have correct data for their programs, curriculum maps and measurement maps.  The Department Contributor Guide is an important document for training the departmental reps.

Please update and modify the Department Contributors Guide as originally written by Evan.  You can find the latest version of the guide at:

https://github.com/smiths/MEASURE/blob/master/McMaster%20Vena%20Contributor%20Guide%20-%20Department.docx

Ideally it would be great if you could commit any changes back using git, but for now, you can e-mail me the new version of the file and I'll push it to the repo.

Besides improving the flow and the English, could you please add the following:
- instructions on sharing courses (you and Evan did this for the Eng 1 courses, I believe)
- explain check-in and check-out
- point to instructions for installing the Vena add in
- instructions for posting issues/questions on our Google form

**Comment by zhengm2** [comment]
If a course is no longer offered and not in the curriculum, what is the best way to handle this? Deleting it seems like it will erase the past data as well. This information is not included in the guide.

![capture](https://cloud.githubusercontent.com/assets/20647879/19529654/e0607266-95fe-11e6-950e-e2cfb6717f30.JPG)

**Comment by smiths** [comment]
@EvanVena can hopefully confirm this, but I do not see any reason to delete a course.  We don't want to lose the data for previous rubrics and course reports.  Each program has a mapping to what courses are in the program.  In cases like this, we should just not include the course in the program mapping.

**Comment by zhengm2** [comment]
Hi @smiths, I've uploaded the department guide to the repo and it is ready for your review. All of the changes you have recommended have been included. I also cleaned up the formatting a little and can make additional cosmetic changes in the future. The only thing left for the department guide is to update the Section Guide in the timeline once the other manuals are complete.

**Comment by smiths** [comment]
Sounds good.  Thank you Michelle.

**Comment by smiths** [comment]
Hello Michelle.  I just made some very minor edits to the departmental guide and the admin guide.  You should do a fresh pull from the repo before editing either of these documents.
