### ISSUE TITLE
Update McMaster Vena Contributor Guide - Instructor.docx

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#80]
We need to improve the instructions given in the McMaster Vena Contributor Guide - Instructor.docx.  The most up to date version can be found at:

https://github.com/smiths/MEASURE/blob/master/McMaster%20Vena%20Contributor%20Guide%20-%20Instructor.docx

When you are done making your edits, please e-mail it to me and I'll push it back to the repo.

The changes to make to the instructors manual are as follows:
- make it easier to follow
- improve the English
- make it clear that the instructors add information to two templates: the rubric template and the course report
- explain step-by-step how to open a template, include information on clicking on "Enable Editing", displaying by courses, not by programs, adding line items to an indicator, what to do if an indicator is missing, etc.
- explain check-in and check-out
- go through each item of the Vena tab in Excel and either explain it, or state that it is not of interest for typical instructor tasks
- add the instructions for the installing the Vena add in
- add instructions for a google form for people to report issues/questions

**Comment by zhengm2** [comment]
Hi @smiths ,

I have made a first attempt at this and will be pushing my copy to the repo shortly. I have a couple of concerns that maybe you could clarify for me:
1. Section 5 of the guide is Reports. It was in there initially so I left it in but I'm unsure if instructors need to access the Curriculum Committee Recommendations Report.
2. The text for section 4.2 course report needs to be modified. Is it mandatory for all instructors to enter continuous improvement plans?

Thanks,
Michelle

**Comment by smiths** [comment]
Hello Michelle.  Thank you for your questions.  Yes, please include the section on reports.  Instructors might not be interested in all of the reports, but I think we should share information with anyone that is interested in pursuing it.  The Curriculum Committee Recommendation Report is actually one that absolutely needs to be included, since this is where instructors find out if their department has recommendations for them to follow.  Instructors should consult this report at the beginning of every term.

In answer to your question, yes it is mandatory for all instructors to enter the continuous improvement plan.  (I'm assuming that you mean filling in the Course Report.)  It is central to the accreditation process that we show that we are taking steps for continual improvement.  Instructors might not put much information here, but they need to enter something.  Please make sure that the documentation reflects this.

**Comment by zhengm2** [comment]
Thanks @smith . I have updated the guide and will push it to the repo for review.

**Comment by smiths** [comment]
Thank you Michelle.  I'll try to find some time soon to review the document.

**Comment by smiths** [comment]
I have now reviewed the document and made changes.  I added additional information and screen shots.  For the reports I removed the ones that should be covered in the Departmental guide.  I made a corresponding change to the Departmental guide so that it doesn't discuss reports that are in the Instructor guides.
