### ISSUE TITLE
Remove "Edit Courses and Program Mapping"

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#84]
The section of the Admin Guide "Edit Courses and Program Mapping" should be removed.  This section should only exist in the Departmental Guide.  We don't want to maintain the information in two places, and it will usually be the departments that are doing this step.

**Comment by zhengm2** [comment]
Updated

**Comment by smiths** [comment]
Hi Michelle.  I did a bit of research and I think that it will be easy for your to upload your revised files to the repo.  I originally thought that this would require additional tools, but it turns out that you can do it through the browser.  If you get a chance to try, you can find the instructions at the following link:

https://github.com/blog/2105-upload-files-to-your-repositories

If you would rather just e-mail the files to me after you make changes, that is still fine.
