### ISSUE TITLE
Move the Section for Adding a New Course to the Departmental Guide

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#85]
The department's will usually be the ones that are adding new courses, so this section of the guide should be moved to the Departmental Guide.

**Comment by zhengm2** [comment]
I've added the original instructions. However, I'm still waiting to hear back from Evan #24 to see if this is the correct process as I couldn't get it to work. I will update accordingly once I hear back from him.

**Comment by smiths** [comment]
Sounds good Michelle.  I have a phone conversation scheduled with Evan for Wednesday.  I will ask him about the instructions at that time.
