### ISSUE TITLE
Add Section for Adding Courses

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#86]
We need to add a section to the Department Guide for Adding Courses.  This section was originally in the Admin Guide, as mentioned in #85.  This section will need to be corrected based on the information provided by @EvanVena, since the instructions currently seem to be incorrect.

**Comment by EvanVena** [comment]
Added,
Please see the attached document.

Evan

**Comment by smiths** [comment]
Hello @EvanVena.  There is not attached document.   I did a bit of research and I think that it will be easy for your to upload your revised files to the repo, rather than attach them to issue comments. I originally thought that this would require additional tools, but it turns out that you can do it through the browser. If you get a chance to try, you can find the instructions at the following link:

https://github.com/blog/2105-upload-files-to-your-repositories

If you would rather just e-mail the files to me after you make changes, that is still fine.

**Comment by EvanVena** [comment]
I just upload again to the Github, can you please take a look

**Comment by smiths** [comment]
The section in question is now in the correct document, so I am going to close this issue.  Once @zhengm2 confirms that the instructions fit her needs, we can also close #24 .
