### ISSUE TITLE
Reference Mac User Instructions in Instructor's Guide

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#87]
The Instructor Guide should point to the instructions for Mac Users.  We shouldn't reproduce the instructions in the manual, since they are not relevant for everyone.  Rather we should point to the instructions for those who will find them relevant.

We have not set it up yet, but I think we should put all documents on a web-page.  The web-page can be where instructors go to find their documents.

**Comment by zhengm2** [comment]
Hi Spencer, I have added the text in. Once we determine where it will be available I can update the document with the link. I'll leave this issue open for now so that I don't forget about it.

**Comment by smiths** [comment]
Hello Michelle.  I haven't posted it yet, but we'll put the instructions up at the following link:

http://measure.mcmaster.ca/

I don't see the link changing, so I think you can go ahead and add it to the documentation.

**Comment by zhengm2** [comment]
Thanks @smiths! I have included this in the instructor guide and the department guide.

**Comment by smiths** [comment]
Thank you.
