### ISSUE TITLE
Names of Departmental Reps

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#88]
Hello Michelle.  Can you please provide @EvanVena with the list of departmental reps?  He needs this list to make sure that they can all see the curriculum map and measurement map.  They will also need to be able to edit the mapping between the programs and the courses.  Evan has asked for the information in the following format:

![image](https://cloud.githubusercontent.com/assets/1422000/19878726/a074056e-9fc2-11e6-813a-2e51c0853241.png)

I'm sure you are really busy with getting back from your holidays, but the sooner we can get the information to Evan, the sooner he can help us get everyone set up in MEASURE.

**Comment by zhengm2** [comment]
![department reps](https://cloud.githubusercontent.com/assets/20647879/19946093/5704468e-a119-11e6-8e96-d7c4229f5a63.JPG)

**Comment by zhengm2** [comment]
Hi @EvanVena, I've attached an image of the information. If you need any additional information please let me know. I will update this once I hear back from Materials Engineering.

Thank you!

**Comment by smiths** [comment]
Thank you Michelle.  If you require additional information Evan (@EvanVena) please let us know.

**Comment by zhengm2** [comment]
@EvanVena Hannah Abram is the Task Owner for Materials Engineering.

**Comment by EvanVena** [comment]
@zhengm2 @smiths @bhancas 
Done,
![image](https://cloud.githubusercontent.com/assets/20912011/20248185/6b83f19a-a9ac-11e6-95c8-058c51aa1901.png)

**Comment by smiths** [comment]
Thank you Evan.  @zhengm2 , can you please verify and then close this issue?  Thank you.

**Comment by zhengm2** [comment]
Everything looks correct. All department reps have been set up and have contributor access.

**Comment by smiths** [comment]
Great!  Thank you Evan and Michelle.
