### ISSUE TITLE
Add Documentation for Updating Valid Course Information

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#89]
Once issue #66 has been addressed, we will have to update the Departmental documentation so that the department administrators can update the valid course information.  If I understand correctly, the information that summarizes the valid courses (valid course/section/term combinations) will be in a spreadsheet.  We have to let the department's know what spreadsheet is being used and how to update it.

If possible, I would like @EvanVena to do the first draft of the documentation and @zhengm2 to test it and provide an editing pass.

**Comment by EvanVena** [comment]
@smiths @bhancas Done, and upload back to Github

**Comment by smiths** [comment]
Thank you @EvanVena for adding the information on editing the valid terms and sections.  I verified that I can follow the instructions.  I noticed a few minor problems.  The term "sheet navigation area" won't be known to everyone.  Could you please refer to it as "sheet navigation area via the tab at the bottom of the spreadsheet" or something similar.  Also, CourseList is misspelled.  Thank you Evan.

**Comment by smiths** [comment]
Hello @EvanVena .  When I look at the CourseList tab, every course seems to just list CHEM 1E03.  Is this what I'm supposed to see?  I thought every course would list itself?  I have checked MECH ENG 4T03 and MECH ENG 2P04, both for 2015-2016, Term 1.

**Comment by EvanVena** [comment]
@smiths 
I added them all, can you please check.
in order for this function to work correctly, the courses code will need to match the Vena Model Course Code. Which currently some of them do not match.
![image](https://cloud.githubusercontent.com/assets/20912011/20762078/37243fbe-b6f3-11e6-9b6b-adb37165093b.png)

**Comment by smiths** [comment]
Hello Evan.  I am confused.  Is this full list of valid course/term/section combinations a hidden tab in every rubric input template?  Is it possible to maintain this information in one spot?  For the question of naming, I think we can correct this.  If there is one place to go to check the information, then I think I can ask @zhengm2 to check it.  Where would that place be?

**Comment by EvanVena** [comment]
@smiths 
In Vena -->Modeler-->Dimensions-->Program

![image](https://cloud.githubusercontent.com/assets/20912011/20771743/b3ea6242-b718-11e6-8e81-18438f48cbbd.png)

**Comment by smiths** [comment]
In addition to documenting how to update the validation information, we'll need to fix the validation information.

**Comment by smiths** [comment]
The documentation is complete on this topic, so I will close this issue.  I'll open a new one for updating the validation rules to match the course name syntax.
