### ISSUE TITLE
Request for a New Measured Indicator Report

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#90]
In looking over the documentation, I realized that the instructors do not have a report that summarizes the indicators that they are expected to measure.  That is, we do not have a "Measurement Map Report."  This information is implied in the rubric template, but I think it would be nice if we had a quick visual of it.  I'm just thinking a report that parallels the Measurement Indicator Map.  We don't want instructors to have access to write to this map, so I was hoping we could have a report version.

Can we have a report version of the "Measured Indicators Map," maybe with a name like "Measurement Map Report"?  The instructors should have have access to the Measured Indicators Map, but they could all see the Measurement Map Report as one of their reports.

**Comment by EvanVena** [comment]
@bhancas @smiths  done.

**Comment by smiths** [comment]
Looks great.  Thank you Evan.  I'll close this issue now.
