### ISSUE TITLE
Add Recommendation for Excel 2013 or later

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#91]
Michelle, for the pre-requisites entry in each of our user manuals, can you please add the recommendation that users use Excel 2013 or later.  Thank you!

**Comment by zhengm2** [comment]
Updated!

**Comment by smiths** [comment]
Great!  Thank you Michelle.  When you edit the documents, can you please upload them to the repo like you did previously.  That way Evan or I can always be reading/editing the most up to date version.
