### ISSUE TITLE
Modify Instructor's Manual to Mention "Measurement Map Report"

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#92]
Hello Michelle.  Can you please add a reference to the new "Measurement Map Report" in the Instructors manual?  This report will allow the instructors to read what indicators they are to measure, without the option to write changes.   This report is discussed further at #90.

**Comment by zhengm2** [comment]
Hi @smiths ,

I have included this in the reports section. Please have a look and let me know if it needs to be moved up.

**Comment by smiths** [comment]
Okay.  I'll review the manual soon.
