### ISSUE TITLE
Faculty Recommendations Input Template

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#94]
Hello Michelle.  Can you please add a section to the Admin guide that explains how to enter data into the Faculty Recommendations Input Template?  The instructions will be similar to those for the Curriculum Committee Recommendations Input Template, as found in the Departmental Guide.

**Comment by zhengm2** [comment]
Hi Spencer, the Admin guide has been updated and pushed to the repo.

**Comment by smiths** [comment]
Looks great.  Thank you Michelle.
