### ISSUE TITLE
Can we delete Section 9 of the Departmental Guide?

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#96]
Hello @EvanVena.  Can we delete Section 9 (Add a New Course to a Process)?  It doesn't seem to apply any more, but maybe I am missing something?

**Comment by EvanVena** [comment]
@smiths @bhancas  Done, and uploaded back at 21/11/2016 2:15 PM

**Comment by smiths** [comment]
Great.  Thank you Evan.  I'll close this issue.
