### ISSUE TITLE
Remove names from list of available resources?

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#97]
Hello @EvanVena and @bhancas.  Would you like me to remove your names from the "Other Vena Resources" section of the departmental guide and the instructors guides?  I don't think we want departments or instructors contacting you directly.  If it is okay with you, I'll leave your names in the administrator's guide, since it would be the administrator (Michelle or myself) that would contact you with questions.

**Comment by EvanVena** [comment]
Updated 21/11/2016 2:20 PM
@smiths @bhancas

**Comment by smiths** [comment]
Hi Evan.  I didn't actually want to remove the other resources section, just the listing of your name and Bogdan's.  I'm going to restore the information from the previous version in the repo.
