### ISSUE TITLE
Graph formatting in Course Report For Large Number of Measurements 

### ISSUE THREAD

**Issue by JoeSpan** [smiths/MEASURE#99]
Something I did not notice before is the formatting when many topics are measured for an indicator the graph generated under detailed chart data labels are overlapping. Is their a way to size the graphs according to the data in them? It would be nice if the graph got bigger as you added more data.   @smiths 
![image](https://cloud.githubusercontent.com/assets/20819724/20373523/5e6fa698-ac40-11e6-9ede-e97d4e615e2e.png)

**Comment by smiths** [comment]
Hello Joe.  Thank you for the screen shot.  It is indeed crowded.  I'm going to assign this issue to Evan.  Your request might be just need a simple fix, or it might be more involved.  Evan will know.

**Comment by EvanVena** [comment]
@smiths @JoeSpan 
There chart size is based on the information in the rubric, so it is not feasible to have one  template to fit all the needs, instead i open the chart area out, so now you have the ability to resize it yourself, and you can also edit the title and the number format inside it,
Hope this will help.
Evan 

![image](https://cloud.githubusercontent.com/assets/20912011/20498784/703fb6f0-affc-11e6-8aba-a1dd630bc91e.png)

**Comment by smiths** [comment]
Thank you @EvanVena .  Yes, I think the ability to resize the chart ourselves is a good way to address this problem.  I'll close this issue now.
